// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        indvars_iv14,
        distances_address0,
        distances_ce0,
        distances_we0,
        distances_d0,
        distances_q0,
        distances_address1,
        distances_ce1,
        distances_we1,
        distances_d1,
        distances_q1,
        labels_address0,
        labels_ce0,
        labels_we0,
        labels_d0,
        labels_q0,
        labels_address1,
        labels_ce1,
        labels_we1,
        labels_d1,
        labels_q1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] indvars_iv14;
output  [10:0] distances_address0;
output   distances_ce0;
output   distances_we0;
output  [63:0] distances_d0;
input  [63:0] distances_q0;
output  [10:0] distances_address1;
output   distances_ce1;
output   distances_we1;
output  [63:0] distances_d1;
input  [63:0] distances_q1;
output  [10:0] labels_address0;
output   labels_ce0;
output   labels_we0;
output  [3:0] labels_d0;
input  [3:0] labels_q0;
output  [10:0] labels_address1;
output   labels_ce1;
output   labels_we1;
output  [3:0] labels_d1;
input  [3:0] labels_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln65_fu_120_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state5;
reg   [0:0] icmp_ln65_reg_235;
wire   [10:0] add_ln66_fu_126_p2;
reg   [10:0] add_ln66_reg_239;
wire   [63:0] zext_ln65_fu_132_p1;
reg   [63:0] zext_ln65_reg_244;
reg   [10:0] distances_addr_reg_249;
wire   [63:0] zext_ln66_fu_137_p1;
reg   [63:0] zext_ln66_reg_254;
reg   [10:0] distances_addr_1_reg_259;
reg   [63:0] temp_dist_reg_264;
wire    ap_CS_fsm_state2;
reg   [63:0] distances_load_1_reg_271;
wire   [0:0] and_ln66_1_fu_218_p2;
reg   [0:0] and_ln66_1_reg_278;
wire    ap_CS_fsm_state4;
reg   [10:0] labels_addr_reg_282;
reg   [10:0] labels_addr_1_reg_287;
reg   [10:0] j_fu_46;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    distances_ce1_local;
reg   [10:0] distances_address1_local;
reg    distances_ce0_local;
reg   [10:0] distances_address0_local;
reg    distances_we1_local;
reg    distances_we0_local;
reg    labels_ce1_local;
reg   [10:0] labels_address1_local;
reg    labels_ce0_local;
reg   [10:0] labels_address0_local;
reg    labels_we1_local;
reg    labels_we0_local;
wire    ap_CS_fsm_state3;
wire   [63:0] bitcast_ln66_fu_142_p1;
wire   [63:0] bitcast_ln66_1_fu_159_p1;
wire   [10:0] tmp_1_fu_145_p4;
wire   [51:0] trunc_ln66_fu_155_p1;
wire   [0:0] icmp_ln66_1_fu_182_p2;
wire   [0:0] icmp_ln66_fu_176_p2;
wire   [10:0] tmp_2_fu_162_p4;
wire   [51:0] trunc_ln66_1_fu_172_p1;
wire   [0:0] icmp_ln66_3_fu_200_p2;
wire   [0:0] icmp_ln66_2_fu_194_p2;
wire   [0:0] or_ln66_fu_188_p2;
wire   [0:0] or_ln66_1_fu_206_p2;
wire   [0:0] and_ln66_fu_212_p2;
wire   [0:0] grp_fu_108_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 j_fu_46 = 11'd0;
#0 ap_done_reg = 1'b0;
end

knn_accelerator_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_dist_reg_264),
    .din1(distances_load_1_reg_271),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_108_p2)
);

knn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        j_fu_46 <= 11'd0;
    end else if (((icmp_ln65_reg_235 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        j_fu_46 <= add_ln66_reg_239;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln66_reg_239 <= add_ln66_fu_126_p2;
        distances_addr_1_reg_259 <= zext_ln66_fu_137_p1;
        distances_addr_reg_249 <= zext_ln65_fu_132_p1;
        icmp_ln65_reg_235 <= icmp_ln65_fu_120_p2;
        zext_ln65_reg_244[10 : 0] <= zext_ln65_fu_132_p1[10 : 0];
        zext_ln66_reg_254[10 : 0] <= zext_ln66_fu_137_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        and_ln66_1_reg_278 <= and_ln66_1_fu_218_p2;
        labels_addr_1_reg_287 <= zext_ln66_reg_254;
        labels_addr_reg_282 <= zext_ln65_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        distances_load_1_reg_271 <= distances_q0;
        temp_dist_reg_264 <= distances_q1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln65_fu_120_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_46;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        distances_address0_local = distances_addr_1_reg_259;
    end else if (((icmp_ln65_fu_120_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        distances_address0_local = zext_ln66_fu_137_p1;
    end else begin
        distances_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        distances_address1_local = distances_addr_reg_249;
    end else if (((icmp_ln65_fu_120_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        distances_address1_local = zext_ln65_fu_132_p1;
    end else begin
        distances_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln65_fu_120_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        distances_ce0_local = 1'b1;
    end else begin
        distances_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln65_fu_120_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        distances_ce1_local = 1'b1;
    end else begin
        distances_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        distances_we0_local = 1'b1;
    end else begin
        distances_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        distances_we1_local = 1'b1;
    end else begin
        distances_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        labels_address0_local = labels_addr_1_reg_287;
    end else if (((1'd1 == and_ln66_1_fu_218_p2) & (1'b1 == ap_CS_fsm_state4))) begin
        labels_address0_local = zext_ln66_reg_254;
    end else begin
        labels_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        labels_address1_local = labels_addr_reg_282;
    end else if (((1'd1 == and_ln66_1_fu_218_p2) & (1'b1 == ap_CS_fsm_state4))) begin
        labels_address1_local = zext_ln65_reg_244;
    end else begin
        labels_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5)) | ((1'd1 == and_ln66_1_fu_218_p2) & (1'b1 == ap_CS_fsm_state4)))) begin
        labels_ce0_local = 1'b1;
    end else begin
        labels_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5)) | ((1'd1 == and_ln66_1_fu_218_p2) & (1'b1 == ap_CS_fsm_state4)))) begin
        labels_ce1_local = 1'b1;
    end else begin
        labels_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        labels_we0_local = 1'b1;
    end else begin
        labels_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_reg_235 == 1'd0) & (1'd1 == and_ln66_1_reg_278) & (1'b1 == ap_CS_fsm_state5))) begin
        labels_we1_local = 1'b1;
    end else begin
        labels_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln65_fu_120_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln66_fu_126_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign and_ln66_1_fu_218_p2 = (grp_fu_108_p2 & and_ln66_fu_212_p2);

assign and_ln66_fu_212_p2 = (or_ln66_fu_188_p2 & or_ln66_1_fu_206_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln66_1_fu_159_p1 = distances_load_1_reg_271;

assign bitcast_ln66_fu_142_p1 = temp_dist_reg_264;

assign distances_address0 = distances_address0_local;

assign distances_address1 = distances_address1_local;

assign distances_ce0 = distances_ce0_local;

assign distances_ce1 = distances_ce1_local;

assign distances_d0 = temp_dist_reg_264;

assign distances_d1 = distances_load_1_reg_271;

assign distances_we0 = distances_we0_local;

assign distances_we1 = distances_we1_local;

assign icmp_ln65_fu_120_p2 = ((ap_sig_allocacmp_j_1 == indvars_iv14) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_182_p2 = ((trunc_ln66_fu_155_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_194_p2 = ((tmp_2_fu_162_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_200_p2 = ((trunc_ln66_1_fu_172_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_176_p2 = ((tmp_1_fu_145_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign labels_address0 = labels_address0_local;

assign labels_address1 = labels_address1_local;

assign labels_ce0 = labels_ce0_local;

assign labels_ce1 = labels_ce1_local;

assign labels_d0 = labels_q1;

assign labels_d1 = labels_q0;

assign labels_we0 = labels_we0_local;

assign labels_we1 = labels_we1_local;

assign or_ln66_1_fu_206_p2 = (icmp_ln66_3_fu_200_p2 | icmp_ln66_2_fu_194_p2);

assign or_ln66_fu_188_p2 = (icmp_ln66_fu_176_p2 | icmp_ln66_1_fu_182_p2);

assign tmp_1_fu_145_p4 = {{bitcast_ln66_fu_142_p1[62:52]}};

assign tmp_2_fu_162_p4 = {{bitcast_ln66_1_fu_159_p1[62:52]}};

assign trunc_ln66_1_fu_172_p1 = bitcast_ln66_1_fu_159_p1[51:0];

assign trunc_ln66_fu_155_p1 = bitcast_ln66_fu_142_p1[51:0];

assign zext_ln65_fu_132_p1 = ap_sig_allocacmp_j_1;

assign zext_ln66_fu_137_p1 = add_ln66_fu_126_p2;

always @ (posedge ap_clk) begin
    zext_ln65_reg_244[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln66_reg_254[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j
