// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module knn_accelerator_knn_majority_vote (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        top_k_labels_read,
        top_k_labels_read_8,
        top_k_labels_read_9,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] top_k_labels_read;
input  [3:0] top_k_labels_read_8;
input  [3:0] top_k_labels_read_9;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] counts_addr_1_reg_318;
wire    ap_CS_fsm_state3;
reg   [3:0] i_5_reg_343;
wire    ap_CS_fsm_state5;
wire   [31:0] counts_q0;
wire   [63:0] zext_ln101_fu_146_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln101_fu_134_p2;
wire   [63:0] zext_ln116_fu_193_p1;
wire   [0:0] icmp_ln113_fu_164_p2;
wire   [63:0] zext_ln127_fu_235_p1;
wire   [0:0] icmp_ln127_fu_223_p2;
reg   [3:0] i_fu_54;
wire   [3:0] add_ln101_fu_140_p2;
reg   [1:0] i_1_fu_62;
wire   [1:0] add_ln113_fu_170_p2;
reg   [31:0] max_fu_66;
wire   [31:0] max_1_fu_254_p3;
wire    ap_CS_fsm_state6;
reg   [31:0] max_label_fu_70;
wire   [31:0] max_label_1_fu_265_p3;
reg   [3:0] i_2_fu_74;
wire   [3:0] add_ln127_fu_229_p2;
reg    counts_we0_local;
reg   [31:0] counts_d0_local;
reg    counts_ce0_local;
reg   [3:0] counts_address0_local;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln116_fu_213_p2;
wire   [3:0] idx_fu_176_p7;
wire   [3:0] idx_fu_176_p9;
wire   [0:0] icmp_ln129_fu_248_p2;
wire   [31:0] zext_ln129_fu_262_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire   [1:0] idx_fu_176_p1;
wire   [1:0] idx_fu_176_p3;
wire  signed [1:0] idx_fu_176_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 i_fu_54 = 4'd0;
#0 i_1_fu_62 = 2'd0;
#0 max_fu_66 = 32'd0;
#0 max_label_fu_70 = 32'd0;
#0 i_2_fu_74 = 4'd0;
end

knn_accelerator_knn_majority_vote_counts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
counts_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(counts_address0_local),
    .ce0(counts_ce0_local),
    .we0(counts_we0_local),
    .d0(counts_d0_local),
    .q0(counts_q0)
);

(* dissolve_hierarchy = "yes" *) knn_accelerator_sparsemux_7_2_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 4 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 4 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
sparsemux_7_2_4_1_1_U34(
    .din0(top_k_labels_read),
    .din1(top_k_labels_read_8),
    .din2(top_k_labels_read_9),
    .def(idx_fu_176_p7),
    .sel(i_1_fu_62),
    .dout(idx_fu_176_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln101_fu_134_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_fu_62 <= 2'd0;
    end else if (((icmp_ln113_fu_164_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_1_fu_62 <= add_ln113_fu_170_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_164_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_2_fu_74 <= 4'd0;
    end else if (((icmp_ln127_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_2_fu_74 <= add_ln127_fu_229_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_54 <= 4'd0;
    end else if (((icmp_ln101_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_54 <= add_ln101_fu_140_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln113_fu_164_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        max_fu_66 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        max_fu_66 <= max_1_fu_254_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        counts_addr_1_reg_318 <= zext_ln116_fu_193_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_5_reg_343 <= i_2_fu_74;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        max_label_fu_70 <= max_label_1_fu_265_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((icmp_ln127_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln127_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        counts_address0_local = zext_ln127_fu_235_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_address0_local = counts_addr_1_reg_318;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        counts_address0_local = zext_ln116_fu_193_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        counts_address0_local = zext_ln101_fu_146_p1;
    end else begin
        counts_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        counts_ce0_local = 1'b1;
    end else begin
        counts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_d0_local = add_ln116_fu_213_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        counts_d0_local = 32'd0;
    end else begin
        counts_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((icmp_ln101_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        counts_we0_local = 1'b1;
    end else begin
        counts_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln101_fu_134_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln113_fu_164_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln127_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_fu_140_p2 = (i_fu_54 + 4'd1);

assign add_ln113_fu_170_p2 = (i_1_fu_62 + 2'd1);

assign add_ln116_fu_213_p2 = (counts_q0 + 32'd1);

assign add_ln127_fu_229_p2 = (i_2_fu_74 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_return = max_label_fu_70;

assign icmp_ln101_fu_134_p2 = ((i_fu_54 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_164_p2 = ((i_1_fu_62 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_223_p2 = ((i_2_fu_74 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln129_fu_248_p2 = (($signed(counts_q0) > $signed(max_fu_66)) ? 1'b1 : 1'b0);

assign idx_fu_176_p7 = 'bx;

assign max_1_fu_254_p3 = ((icmp_ln129_fu_248_p2[0:0] == 1'b1) ? counts_q0 : max_fu_66);

assign max_label_1_fu_265_p3 = ((icmp_ln129_fu_248_p2[0:0] == 1'b1) ? zext_ln129_fu_262_p1 : max_label_fu_70);

assign zext_ln101_fu_146_p1 = i_fu_54;

assign zext_ln116_fu_193_p1 = idx_fu_176_p9;

assign zext_ln127_fu_235_p1 = i_2_fu_74;

assign zext_ln129_fu_262_p1 = i_5_reg_343;

endmodule //knn_accelerator_knn_majority_vote
