// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        distances_address0,
        distances_ce0,
        distances_we0,
        distances_d0,
        distances_q0,
        distances_address1,
        distances_ce1,
        distances_we1,
        distances_d1,
        distances_q1,
        labels_address0,
        labels_ce0,
        labels_we0,
        labels_d0,
        labels_q0,
        labels_address1,
        labels_ce1,
        labels_we1,
        labels_d1,
        labels_q1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] distances_address0;
output   distances_ce0;
output   distances_we0;
output  [63:0] distances_d0;
input  [63:0] distances_q0;
output  [10:0] distances_address1;
output   distances_ce1;
output   distances_we1;
output  [63:0] distances_d1;
input  [63:0] distances_q1;
output  [10:0] labels_address0;
output   labels_ce0;
output   labels_we0;
output  [3:0] labels_d0;
input  [3:0] labels_q0;
output  [10:0] labels_address1;
output   labels_ce1;
output   labels_we1;
output  [3:0] labels_d1;
input  [3:0] labels_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] indvars_iv14_load_reg_103;
wire    ap_CS_fsm_state2;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_idle;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_ready;
wire   [10:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address0;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce0;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we0;
wire   [63:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d0;
wire   [10:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address1;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce1;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we1;
wire   [63:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d1;
wire   [10:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address0;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce0;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we0;
wire   [3:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d0;
wire   [10:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address1;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce1;
wire    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we1;
wire   [3:0] grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d1;
reg    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg;
wire   [0:0] icmp_ln64_fu_54_p2;
wire    ap_CS_fsm_state3;
reg   [10:0] i_4_fu_24;
wire   [10:0] i_6_fu_60_p2;
reg   [10:0] indvars_iv14_fu_28;
wire   [10:0] add_ln64_fu_70_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg = 1'b0;
#0 i_4_fu_24 = 11'd0;
#0 indvars_iv14_fu_28 = 11'd0;
end

knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start),
    .ap_done(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done),
    .ap_idle(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_idle),
    .ap_ready(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_ready),
    .indvars_iv14(indvars_iv14_load_reg_103),
    .distances_address0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address0),
    .distances_ce0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce0),
    .distances_we0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we0),
    .distances_d0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d0),
    .distances_q0(distances_q0),
    .distances_address1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address1),
    .distances_ce1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce1),
    .distances_we1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we1),
    .distances_d1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d1),
    .distances_q1(distances_q1),
    .labels_address0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address0),
    .labels_ce0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce0),
    .labels_we0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we0),
    .labels_d0(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d0),
    .labels_q0(labels_q0),
    .labels_address1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address1),
    .labels_ce1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce1),
    .labels_we1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we1),
    .labels_d1(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d1),
    .labels_q1(labels_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln64_fu_54_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_ready == 1'b1)) begin
            grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_4_fu_24 <= 11'd0;
    end else if (((icmp_ln64_fu_54_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_4_fu_24 <= i_6_fu_60_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvars_iv14_fu_28 <= 11'd1499;
    end else if (((icmp_ln64_fu_54_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvars_iv14_fu_28 <= add_ln64_fu_70_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        indvars_iv14_load_reg_103 <= indvars_iv14_fu_28;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln64_fu_54_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_54_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln64_fu_54_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_70_p2 = ($signed(indvars_iv14_fu_28) + $signed(11'd2047));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign distances_address0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address0;

assign distances_address1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address1;

assign distances_ce0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce0;

assign distances_ce1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce1;

assign distances_d0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d0;

assign distances_d1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d1;

assign distances_we0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we0;

assign distances_we1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we1;

assign grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg;

assign i_6_fu_60_p2 = (i_4_fu_24 + 11'd1);

assign icmp_ln64_fu_54_p2 = ((i_4_fu_24 == 11'd1499) ? 1'b1 : 1'b0);

assign labels_address0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address0;

assign labels_address1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address1;

assign labels_ce0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce0;

assign labels_ce1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce1;

assign labels_d0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d0;

assign labels_d1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d1;

assign labels_we0 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we0;

assign labels_we1 = grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we1;

endmodule //knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i
