-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    distances_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    distances_ce0 : OUT STD_LOGIC;
    distances_we0 : OUT STD_LOGIC;
    distances_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    distances_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    distances_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    distances_ce1 : OUT STD_LOGIC;
    distances_we1 : OUT STD_LOGIC;
    distances_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    distances_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    labels_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_ce0 : OUT STD_LOGIC;
    labels_we0 : OUT STD_LOGIC;
    labels_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    labels_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_ce1 : OUT STD_LOGIC;
    labels_we1 : OUT STD_LOGIC;
    labels_d1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_q1 : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvars_iv14_load_reg_103 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_idle : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_ready : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce0 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we0 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce1 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we1 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce0 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we0 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce1 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we1 : STD_LOGIC;
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln64_fu_54_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_4_fu_24 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_6_fu_60_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvars_iv14_fu_28 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln64_fu_70_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        indvars_iv14 : IN STD_LOGIC_VECTOR (3 downto 0);
        distances_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        distances_ce0 : OUT STD_LOGIC;
        distances_we0 : OUT STD_LOGIC;
        distances_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        distances_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        distances_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        distances_ce1 : OUT STD_LOGIC;
        distances_we1 : OUT STD_LOGIC;
        distances_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        distances_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        labels_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        labels_ce0 : OUT STD_LOGIC;
        labels_we0 : OUT STD_LOGIC;
        labels_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        labels_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
        labels_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        labels_ce1 : OUT STD_LOGIC;
        labels_we1 : OUT STD_LOGIC;
        labels_d1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        labels_q1 : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32 : component knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start,
        ap_done => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done,
        ap_idle => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_idle,
        ap_ready => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_ready,
        indvars_iv14 => indvars_iv14_load_reg_103,
        distances_address0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address0,
        distances_ce0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce0,
        distances_we0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we0,
        distances_d0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d0,
        distances_q0 => distances_q0,
        distances_address1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address1,
        distances_ce1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce1,
        distances_we1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we1,
        distances_d1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d1,
        distances_q1 => distances_q1,
        labels_address0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address0,
        labels_ce0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce0,
        labels_we0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we0,
        labels_d0 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d0,
        labels_q0 => labels_q0,
        labels_address1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address1,
        labels_ce1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce1,
        labels_we1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we1,
        labels_d1 => grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d1,
        labels_q1 => labels_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln64_fu_54_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_ready = ap_const_logic_1)) then 
                    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_4_fu_24_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_4_fu_24 <= ap_const_lv4_0;
            elsif (((icmp_ln64_fu_54_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_4_fu_24 <= i_6_fu_60_p2;
            end if; 
        end if;
    end process;

    indvars_iv14_fu_28_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvars_iv14_fu_28 <= ap_const_lv4_9;
            elsif (((icmp_ln64_fu_54_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvars_iv14_fu_28 <= add_ln64_fu_70_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                indvars_iv14_load_reg_103 <= indvars_iv14_fu_28;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done, icmp_ln64_fu_54_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln64_fu_54_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln64_fu_70_p2 <= std_logic_vector(unsigned(indvars_iv14_fu_28) + unsigned(ap_const_lv4_F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done)
    begin
        if ((grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln64_fu_54_p2)
    begin
        if ((((icmp_ln64_fu_54_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln64_fu_54_p2)
    begin
        if (((icmp_ln64_fu_54_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    distances_address0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address0;
    distances_address1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_address1;
    distances_ce0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce0;
    distances_ce1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_ce1;
    distances_d0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d0;
    distances_d1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_d1;
    distances_we0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we0;
    distances_we1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_distances_we1;
    grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_ap_start_reg;
    i_6_fu_60_p2 <= std_logic_vector(unsigned(i_4_fu_24) + unsigned(ap_const_lv4_1));
    icmp_ln64_fu_54_p2 <= "1" when (i_4_fu_24 = ap_const_lv4_9) else "0";
    labels_address0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address0;
    labels_address1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_address1;
    labels_ce0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce0;
    labels_ce1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_ce1;
    labels_d0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d0;
    labels_d1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_d1;
    labels_we0 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we0;
    labels_we1 <= grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32_labels_we1;
end behav;
