// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="knn_accelerator_knn_accelerator,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=122547,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=5614,HLS_SYN_LUT=7581,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module knn_accelerator (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_x_test_AWVALID,
        m_axi_gmem_x_test_AWREADY,
        m_axi_gmem_x_test_AWADDR,
        m_axi_gmem_x_test_AWID,
        m_axi_gmem_x_test_AWLEN,
        m_axi_gmem_x_test_AWSIZE,
        m_axi_gmem_x_test_AWBURST,
        m_axi_gmem_x_test_AWLOCK,
        m_axi_gmem_x_test_AWCACHE,
        m_axi_gmem_x_test_AWPROT,
        m_axi_gmem_x_test_AWQOS,
        m_axi_gmem_x_test_AWREGION,
        m_axi_gmem_x_test_AWUSER,
        m_axi_gmem_x_test_WVALID,
        m_axi_gmem_x_test_WREADY,
        m_axi_gmem_x_test_WDATA,
        m_axi_gmem_x_test_WSTRB,
        m_axi_gmem_x_test_WLAST,
        m_axi_gmem_x_test_WID,
        m_axi_gmem_x_test_WUSER,
        m_axi_gmem_x_test_ARVALID,
        m_axi_gmem_x_test_ARREADY,
        m_axi_gmem_x_test_ARADDR,
        m_axi_gmem_x_test_ARID,
        m_axi_gmem_x_test_ARLEN,
        m_axi_gmem_x_test_ARSIZE,
        m_axi_gmem_x_test_ARBURST,
        m_axi_gmem_x_test_ARLOCK,
        m_axi_gmem_x_test_ARCACHE,
        m_axi_gmem_x_test_ARPROT,
        m_axi_gmem_x_test_ARQOS,
        m_axi_gmem_x_test_ARREGION,
        m_axi_gmem_x_test_ARUSER,
        m_axi_gmem_x_test_RVALID,
        m_axi_gmem_x_test_RREADY,
        m_axi_gmem_x_test_RDATA,
        m_axi_gmem_x_test_RLAST,
        m_axi_gmem_x_test_RID,
        m_axi_gmem_x_test_RUSER,
        m_axi_gmem_x_test_RRESP,
        m_axi_gmem_x_test_BVALID,
        m_axi_gmem_x_test_BREADY,
        m_axi_gmem_x_test_BRESP,
        m_axi_gmem_x_test_BID,
        m_axi_gmem_x_test_BUSER,
        m_axi_gmem_x_train_AWVALID,
        m_axi_gmem_x_train_AWREADY,
        m_axi_gmem_x_train_AWADDR,
        m_axi_gmem_x_train_AWID,
        m_axi_gmem_x_train_AWLEN,
        m_axi_gmem_x_train_AWSIZE,
        m_axi_gmem_x_train_AWBURST,
        m_axi_gmem_x_train_AWLOCK,
        m_axi_gmem_x_train_AWCACHE,
        m_axi_gmem_x_train_AWPROT,
        m_axi_gmem_x_train_AWQOS,
        m_axi_gmem_x_train_AWREGION,
        m_axi_gmem_x_train_AWUSER,
        m_axi_gmem_x_train_WVALID,
        m_axi_gmem_x_train_WREADY,
        m_axi_gmem_x_train_WDATA,
        m_axi_gmem_x_train_WSTRB,
        m_axi_gmem_x_train_WLAST,
        m_axi_gmem_x_train_WID,
        m_axi_gmem_x_train_WUSER,
        m_axi_gmem_x_train_ARVALID,
        m_axi_gmem_x_train_ARREADY,
        m_axi_gmem_x_train_ARADDR,
        m_axi_gmem_x_train_ARID,
        m_axi_gmem_x_train_ARLEN,
        m_axi_gmem_x_train_ARSIZE,
        m_axi_gmem_x_train_ARBURST,
        m_axi_gmem_x_train_ARLOCK,
        m_axi_gmem_x_train_ARCACHE,
        m_axi_gmem_x_train_ARPROT,
        m_axi_gmem_x_train_ARQOS,
        m_axi_gmem_x_train_ARREGION,
        m_axi_gmem_x_train_ARUSER,
        m_axi_gmem_x_train_RVALID,
        m_axi_gmem_x_train_RREADY,
        m_axi_gmem_x_train_RDATA,
        m_axi_gmem_x_train_RLAST,
        m_axi_gmem_x_train_RID,
        m_axi_gmem_x_train_RUSER,
        m_axi_gmem_x_train_RRESP,
        m_axi_gmem_x_train_BVALID,
        m_axi_gmem_x_train_BREADY,
        m_axi_gmem_x_train_BRESP,
        m_axi_gmem_x_train_BID,
        m_axi_gmem_x_train_BUSER,
        m_axi_gmem_y_train_AWVALID,
        m_axi_gmem_y_train_AWREADY,
        m_axi_gmem_y_train_AWADDR,
        m_axi_gmem_y_train_AWID,
        m_axi_gmem_y_train_AWLEN,
        m_axi_gmem_y_train_AWSIZE,
        m_axi_gmem_y_train_AWBURST,
        m_axi_gmem_y_train_AWLOCK,
        m_axi_gmem_y_train_AWCACHE,
        m_axi_gmem_y_train_AWPROT,
        m_axi_gmem_y_train_AWQOS,
        m_axi_gmem_y_train_AWREGION,
        m_axi_gmem_y_train_AWUSER,
        m_axi_gmem_y_train_WVALID,
        m_axi_gmem_y_train_WREADY,
        m_axi_gmem_y_train_WDATA,
        m_axi_gmem_y_train_WSTRB,
        m_axi_gmem_y_train_WLAST,
        m_axi_gmem_y_train_WID,
        m_axi_gmem_y_train_WUSER,
        m_axi_gmem_y_train_ARVALID,
        m_axi_gmem_y_train_ARREADY,
        m_axi_gmem_y_train_ARADDR,
        m_axi_gmem_y_train_ARID,
        m_axi_gmem_y_train_ARLEN,
        m_axi_gmem_y_train_ARSIZE,
        m_axi_gmem_y_train_ARBURST,
        m_axi_gmem_y_train_ARLOCK,
        m_axi_gmem_y_train_ARCACHE,
        m_axi_gmem_y_train_ARPROT,
        m_axi_gmem_y_train_ARQOS,
        m_axi_gmem_y_train_ARREGION,
        m_axi_gmem_y_train_ARUSER,
        m_axi_gmem_y_train_RVALID,
        m_axi_gmem_y_train_RREADY,
        m_axi_gmem_y_train_RDATA,
        m_axi_gmem_y_train_RLAST,
        m_axi_gmem_y_train_RID,
        m_axi_gmem_y_train_RUSER,
        m_axi_gmem_y_train_RRESP,
        m_axi_gmem_y_train_BVALID,
        m_axi_gmem_y_train_BREADY,
        m_axi_gmem_y_train_BRESP,
        m_axi_gmem_y_train_BID,
        m_axi_gmem_y_train_BUSER,
        m_axi_gmem_y_test_AWVALID,
        m_axi_gmem_y_test_AWREADY,
        m_axi_gmem_y_test_AWADDR,
        m_axi_gmem_y_test_AWID,
        m_axi_gmem_y_test_AWLEN,
        m_axi_gmem_y_test_AWSIZE,
        m_axi_gmem_y_test_AWBURST,
        m_axi_gmem_y_test_AWLOCK,
        m_axi_gmem_y_test_AWCACHE,
        m_axi_gmem_y_test_AWPROT,
        m_axi_gmem_y_test_AWQOS,
        m_axi_gmem_y_test_AWREGION,
        m_axi_gmem_y_test_AWUSER,
        m_axi_gmem_y_test_WVALID,
        m_axi_gmem_y_test_WREADY,
        m_axi_gmem_y_test_WDATA,
        m_axi_gmem_y_test_WSTRB,
        m_axi_gmem_y_test_WLAST,
        m_axi_gmem_y_test_WID,
        m_axi_gmem_y_test_WUSER,
        m_axi_gmem_y_test_ARVALID,
        m_axi_gmem_y_test_ARREADY,
        m_axi_gmem_y_test_ARADDR,
        m_axi_gmem_y_test_ARID,
        m_axi_gmem_y_test_ARLEN,
        m_axi_gmem_y_test_ARSIZE,
        m_axi_gmem_y_test_ARBURST,
        m_axi_gmem_y_test_ARLOCK,
        m_axi_gmem_y_test_ARCACHE,
        m_axi_gmem_y_test_ARPROT,
        m_axi_gmem_y_test_ARQOS,
        m_axi_gmem_y_test_ARREGION,
        m_axi_gmem_y_test_ARUSER,
        m_axi_gmem_y_test_RVALID,
        m_axi_gmem_y_test_RREADY,
        m_axi_gmem_y_test_RDATA,
        m_axi_gmem_y_test_RLAST,
        m_axi_gmem_y_test_RID,
        m_axi_gmem_y_test_RUSER,
        m_axi_gmem_y_test_RRESP,
        m_axi_gmem_y_test_BVALID,
        m_axi_gmem_y_test_BREADY,
        m_axi_gmem_y_test_BRESP,
        m_axi_gmem_y_test_BID,
        m_axi_gmem_y_test_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        s_axi_control_r_AWVALID,
        s_axi_control_r_AWREADY,
        s_axi_control_r_AWADDR,
        s_axi_control_r_WVALID,
        s_axi_control_r_WREADY,
        s_axi_control_r_WDATA,
        s_axi_control_r_WSTRB,
        s_axi_control_r_ARVALID,
        s_axi_control_r_ARREADY,
        s_axi_control_r_ARADDR,
        s_axi_control_r_RVALID,
        s_axi_control_r_RREADY,
        s_axi_control_r_RDATA,
        s_axi_control_r_RRESP,
        s_axi_control_r_BVALID,
        s_axi_control_r_BREADY,
        s_axi_control_r_BRESP
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM_X_TEST_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TEST_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_X_TEST_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_X_TEST_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TEST_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TEST_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TEST_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TEST_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TEST_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_X_TEST_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_X_TEST_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_X_TRAIN_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TRAIN_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_X_TRAIN_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_X_TRAIN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TRAIN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TRAIN_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TRAIN_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TRAIN_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_X_TRAIN_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_X_TRAIN_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_X_TRAIN_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_Y_TEST_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TEST_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_Y_TEST_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_Y_TEST_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TEST_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TEST_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TEST_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TEST_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TEST_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_Y_TEST_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_Y_TEST_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TRAIN_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_Y_TRAIN_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_Y_TRAIN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TRAIN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TRAIN_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TRAIN_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TRAIN_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_Y_TRAIN_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_Y_TRAIN_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_Y_TRAIN_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_X_TEST_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_X_TRAIN_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_GMEM_Y_TEST_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_Y_TRAIN_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_x_test_AWVALID;
input   m_axi_gmem_x_test_AWREADY;
output  [C_M_AXI_GMEM_X_TEST_ADDR_WIDTH - 1:0] m_axi_gmem_x_test_AWADDR;
output  [C_M_AXI_GMEM_X_TEST_ID_WIDTH - 1:0] m_axi_gmem_x_test_AWID;
output  [7:0] m_axi_gmem_x_test_AWLEN;
output  [2:0] m_axi_gmem_x_test_AWSIZE;
output  [1:0] m_axi_gmem_x_test_AWBURST;
output  [1:0] m_axi_gmem_x_test_AWLOCK;
output  [3:0] m_axi_gmem_x_test_AWCACHE;
output  [2:0] m_axi_gmem_x_test_AWPROT;
output  [3:0] m_axi_gmem_x_test_AWQOS;
output  [3:0] m_axi_gmem_x_test_AWREGION;
output  [C_M_AXI_GMEM_X_TEST_AWUSER_WIDTH - 1:0] m_axi_gmem_x_test_AWUSER;
output   m_axi_gmem_x_test_WVALID;
input   m_axi_gmem_x_test_WREADY;
output  [C_M_AXI_GMEM_X_TEST_DATA_WIDTH - 1:0] m_axi_gmem_x_test_WDATA;
output  [C_M_AXI_GMEM_X_TEST_WSTRB_WIDTH - 1:0] m_axi_gmem_x_test_WSTRB;
output   m_axi_gmem_x_test_WLAST;
output  [C_M_AXI_GMEM_X_TEST_ID_WIDTH - 1:0] m_axi_gmem_x_test_WID;
output  [C_M_AXI_GMEM_X_TEST_WUSER_WIDTH - 1:0] m_axi_gmem_x_test_WUSER;
output   m_axi_gmem_x_test_ARVALID;
input   m_axi_gmem_x_test_ARREADY;
output  [C_M_AXI_GMEM_X_TEST_ADDR_WIDTH - 1:0] m_axi_gmem_x_test_ARADDR;
output  [C_M_AXI_GMEM_X_TEST_ID_WIDTH - 1:0] m_axi_gmem_x_test_ARID;
output  [7:0] m_axi_gmem_x_test_ARLEN;
output  [2:0] m_axi_gmem_x_test_ARSIZE;
output  [1:0] m_axi_gmem_x_test_ARBURST;
output  [1:0] m_axi_gmem_x_test_ARLOCK;
output  [3:0] m_axi_gmem_x_test_ARCACHE;
output  [2:0] m_axi_gmem_x_test_ARPROT;
output  [3:0] m_axi_gmem_x_test_ARQOS;
output  [3:0] m_axi_gmem_x_test_ARREGION;
output  [C_M_AXI_GMEM_X_TEST_ARUSER_WIDTH - 1:0] m_axi_gmem_x_test_ARUSER;
input   m_axi_gmem_x_test_RVALID;
output   m_axi_gmem_x_test_RREADY;
input  [C_M_AXI_GMEM_X_TEST_DATA_WIDTH - 1:0] m_axi_gmem_x_test_RDATA;
input   m_axi_gmem_x_test_RLAST;
input  [C_M_AXI_GMEM_X_TEST_ID_WIDTH - 1:0] m_axi_gmem_x_test_RID;
input  [C_M_AXI_GMEM_X_TEST_RUSER_WIDTH - 1:0] m_axi_gmem_x_test_RUSER;
input  [1:0] m_axi_gmem_x_test_RRESP;
input   m_axi_gmem_x_test_BVALID;
output   m_axi_gmem_x_test_BREADY;
input  [1:0] m_axi_gmem_x_test_BRESP;
input  [C_M_AXI_GMEM_X_TEST_ID_WIDTH - 1:0] m_axi_gmem_x_test_BID;
input  [C_M_AXI_GMEM_X_TEST_BUSER_WIDTH - 1:0] m_axi_gmem_x_test_BUSER;
output   m_axi_gmem_x_train_AWVALID;
input   m_axi_gmem_x_train_AWREADY;
output  [C_M_AXI_GMEM_X_TRAIN_ADDR_WIDTH - 1:0] m_axi_gmem_x_train_AWADDR;
output  [C_M_AXI_GMEM_X_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_x_train_AWID;
output  [7:0] m_axi_gmem_x_train_AWLEN;
output  [2:0] m_axi_gmem_x_train_AWSIZE;
output  [1:0] m_axi_gmem_x_train_AWBURST;
output  [1:0] m_axi_gmem_x_train_AWLOCK;
output  [3:0] m_axi_gmem_x_train_AWCACHE;
output  [2:0] m_axi_gmem_x_train_AWPROT;
output  [3:0] m_axi_gmem_x_train_AWQOS;
output  [3:0] m_axi_gmem_x_train_AWREGION;
output  [C_M_AXI_GMEM_X_TRAIN_AWUSER_WIDTH - 1:0] m_axi_gmem_x_train_AWUSER;
output   m_axi_gmem_x_train_WVALID;
input   m_axi_gmem_x_train_WREADY;
output  [C_M_AXI_GMEM_X_TRAIN_DATA_WIDTH - 1:0] m_axi_gmem_x_train_WDATA;
output  [C_M_AXI_GMEM_X_TRAIN_WSTRB_WIDTH - 1:0] m_axi_gmem_x_train_WSTRB;
output   m_axi_gmem_x_train_WLAST;
output  [C_M_AXI_GMEM_X_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_x_train_WID;
output  [C_M_AXI_GMEM_X_TRAIN_WUSER_WIDTH - 1:0] m_axi_gmem_x_train_WUSER;
output   m_axi_gmem_x_train_ARVALID;
input   m_axi_gmem_x_train_ARREADY;
output  [C_M_AXI_GMEM_X_TRAIN_ADDR_WIDTH - 1:0] m_axi_gmem_x_train_ARADDR;
output  [C_M_AXI_GMEM_X_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_x_train_ARID;
output  [7:0] m_axi_gmem_x_train_ARLEN;
output  [2:0] m_axi_gmem_x_train_ARSIZE;
output  [1:0] m_axi_gmem_x_train_ARBURST;
output  [1:0] m_axi_gmem_x_train_ARLOCK;
output  [3:0] m_axi_gmem_x_train_ARCACHE;
output  [2:0] m_axi_gmem_x_train_ARPROT;
output  [3:0] m_axi_gmem_x_train_ARQOS;
output  [3:0] m_axi_gmem_x_train_ARREGION;
output  [C_M_AXI_GMEM_X_TRAIN_ARUSER_WIDTH - 1:0] m_axi_gmem_x_train_ARUSER;
input   m_axi_gmem_x_train_RVALID;
output   m_axi_gmem_x_train_RREADY;
input  [C_M_AXI_GMEM_X_TRAIN_DATA_WIDTH - 1:0] m_axi_gmem_x_train_RDATA;
input   m_axi_gmem_x_train_RLAST;
input  [C_M_AXI_GMEM_X_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_x_train_RID;
input  [C_M_AXI_GMEM_X_TRAIN_RUSER_WIDTH - 1:0] m_axi_gmem_x_train_RUSER;
input  [1:0] m_axi_gmem_x_train_RRESP;
input   m_axi_gmem_x_train_BVALID;
output   m_axi_gmem_x_train_BREADY;
input  [1:0] m_axi_gmem_x_train_BRESP;
input  [C_M_AXI_GMEM_X_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_x_train_BID;
input  [C_M_AXI_GMEM_X_TRAIN_BUSER_WIDTH - 1:0] m_axi_gmem_x_train_BUSER;
output   m_axi_gmem_y_train_AWVALID;
input   m_axi_gmem_y_train_AWREADY;
output  [C_M_AXI_GMEM_Y_TRAIN_ADDR_WIDTH - 1:0] m_axi_gmem_y_train_AWADDR;
output  [C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_y_train_AWID;
output  [7:0] m_axi_gmem_y_train_AWLEN;
output  [2:0] m_axi_gmem_y_train_AWSIZE;
output  [1:0] m_axi_gmem_y_train_AWBURST;
output  [1:0] m_axi_gmem_y_train_AWLOCK;
output  [3:0] m_axi_gmem_y_train_AWCACHE;
output  [2:0] m_axi_gmem_y_train_AWPROT;
output  [3:0] m_axi_gmem_y_train_AWQOS;
output  [3:0] m_axi_gmem_y_train_AWREGION;
output  [C_M_AXI_GMEM_Y_TRAIN_AWUSER_WIDTH - 1:0] m_axi_gmem_y_train_AWUSER;
output   m_axi_gmem_y_train_WVALID;
input   m_axi_gmem_y_train_WREADY;
output  [C_M_AXI_GMEM_Y_TRAIN_DATA_WIDTH - 1:0] m_axi_gmem_y_train_WDATA;
output  [C_M_AXI_GMEM_Y_TRAIN_WSTRB_WIDTH - 1:0] m_axi_gmem_y_train_WSTRB;
output   m_axi_gmem_y_train_WLAST;
output  [C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_y_train_WID;
output  [C_M_AXI_GMEM_Y_TRAIN_WUSER_WIDTH - 1:0] m_axi_gmem_y_train_WUSER;
output   m_axi_gmem_y_train_ARVALID;
input   m_axi_gmem_y_train_ARREADY;
output  [C_M_AXI_GMEM_Y_TRAIN_ADDR_WIDTH - 1:0] m_axi_gmem_y_train_ARADDR;
output  [C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_y_train_ARID;
output  [7:0] m_axi_gmem_y_train_ARLEN;
output  [2:0] m_axi_gmem_y_train_ARSIZE;
output  [1:0] m_axi_gmem_y_train_ARBURST;
output  [1:0] m_axi_gmem_y_train_ARLOCK;
output  [3:0] m_axi_gmem_y_train_ARCACHE;
output  [2:0] m_axi_gmem_y_train_ARPROT;
output  [3:0] m_axi_gmem_y_train_ARQOS;
output  [3:0] m_axi_gmem_y_train_ARREGION;
output  [C_M_AXI_GMEM_Y_TRAIN_ARUSER_WIDTH - 1:0] m_axi_gmem_y_train_ARUSER;
input   m_axi_gmem_y_train_RVALID;
output   m_axi_gmem_y_train_RREADY;
input  [C_M_AXI_GMEM_Y_TRAIN_DATA_WIDTH - 1:0] m_axi_gmem_y_train_RDATA;
input   m_axi_gmem_y_train_RLAST;
input  [C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_y_train_RID;
input  [C_M_AXI_GMEM_Y_TRAIN_RUSER_WIDTH - 1:0] m_axi_gmem_y_train_RUSER;
input  [1:0] m_axi_gmem_y_train_RRESP;
input   m_axi_gmem_y_train_BVALID;
output   m_axi_gmem_y_train_BREADY;
input  [1:0] m_axi_gmem_y_train_BRESP;
input  [C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH - 1:0] m_axi_gmem_y_train_BID;
input  [C_M_AXI_GMEM_Y_TRAIN_BUSER_WIDTH - 1:0] m_axi_gmem_y_train_BUSER;
output   m_axi_gmem_y_test_AWVALID;
input   m_axi_gmem_y_test_AWREADY;
output  [C_M_AXI_GMEM_Y_TEST_ADDR_WIDTH - 1:0] m_axi_gmem_y_test_AWADDR;
output  [C_M_AXI_GMEM_Y_TEST_ID_WIDTH - 1:0] m_axi_gmem_y_test_AWID;
output  [7:0] m_axi_gmem_y_test_AWLEN;
output  [2:0] m_axi_gmem_y_test_AWSIZE;
output  [1:0] m_axi_gmem_y_test_AWBURST;
output  [1:0] m_axi_gmem_y_test_AWLOCK;
output  [3:0] m_axi_gmem_y_test_AWCACHE;
output  [2:0] m_axi_gmem_y_test_AWPROT;
output  [3:0] m_axi_gmem_y_test_AWQOS;
output  [3:0] m_axi_gmem_y_test_AWREGION;
output  [C_M_AXI_GMEM_Y_TEST_AWUSER_WIDTH - 1:0] m_axi_gmem_y_test_AWUSER;
output   m_axi_gmem_y_test_WVALID;
input   m_axi_gmem_y_test_WREADY;
output  [C_M_AXI_GMEM_Y_TEST_DATA_WIDTH - 1:0] m_axi_gmem_y_test_WDATA;
output  [C_M_AXI_GMEM_Y_TEST_WSTRB_WIDTH - 1:0] m_axi_gmem_y_test_WSTRB;
output   m_axi_gmem_y_test_WLAST;
output  [C_M_AXI_GMEM_Y_TEST_ID_WIDTH - 1:0] m_axi_gmem_y_test_WID;
output  [C_M_AXI_GMEM_Y_TEST_WUSER_WIDTH - 1:0] m_axi_gmem_y_test_WUSER;
output   m_axi_gmem_y_test_ARVALID;
input   m_axi_gmem_y_test_ARREADY;
output  [C_M_AXI_GMEM_Y_TEST_ADDR_WIDTH - 1:0] m_axi_gmem_y_test_ARADDR;
output  [C_M_AXI_GMEM_Y_TEST_ID_WIDTH - 1:0] m_axi_gmem_y_test_ARID;
output  [7:0] m_axi_gmem_y_test_ARLEN;
output  [2:0] m_axi_gmem_y_test_ARSIZE;
output  [1:0] m_axi_gmem_y_test_ARBURST;
output  [1:0] m_axi_gmem_y_test_ARLOCK;
output  [3:0] m_axi_gmem_y_test_ARCACHE;
output  [2:0] m_axi_gmem_y_test_ARPROT;
output  [3:0] m_axi_gmem_y_test_ARQOS;
output  [3:0] m_axi_gmem_y_test_ARREGION;
output  [C_M_AXI_GMEM_Y_TEST_ARUSER_WIDTH - 1:0] m_axi_gmem_y_test_ARUSER;
input   m_axi_gmem_y_test_RVALID;
output   m_axi_gmem_y_test_RREADY;
input  [C_M_AXI_GMEM_Y_TEST_DATA_WIDTH - 1:0] m_axi_gmem_y_test_RDATA;
input   m_axi_gmem_y_test_RLAST;
input  [C_M_AXI_GMEM_Y_TEST_ID_WIDTH - 1:0] m_axi_gmem_y_test_RID;
input  [C_M_AXI_GMEM_Y_TEST_RUSER_WIDTH - 1:0] m_axi_gmem_y_test_RUSER;
input  [1:0] m_axi_gmem_y_test_RRESP;
input   m_axi_gmem_y_test_BVALID;
output   m_axi_gmem_y_test_BREADY;
input  [1:0] m_axi_gmem_y_test_BRESP;
input  [C_M_AXI_GMEM_Y_TEST_ID_WIDTH - 1:0] m_axi_gmem_y_test_BID;
input  [C_M_AXI_GMEM_Y_TEST_BUSER_WIDTH - 1:0] m_axi_gmem_y_test_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
input   s_axi_control_r_AWVALID;
output   s_axi_control_r_AWREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_AWADDR;
input   s_axi_control_r_WVALID;
output   s_axi_control_r_WREADY;
input  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_WDATA;
input  [C_S_AXI_CONTROL_R_WSTRB_WIDTH - 1:0] s_axi_control_r_WSTRB;
input   s_axi_control_r_ARVALID;
output   s_axi_control_r_ARREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_ARADDR;
output   s_axi_control_r_RVALID;
input   s_axi_control_r_RREADY;
output  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_RDATA;
output  [1:0] s_axi_control_r_RRESP;
output   s_axi_control_r_BVALID;
input   s_axi_control_r_BREADY;
output  [1:0] s_axi_control_r_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] X_test;
wire   [63:0] X_train;
wire   [63:0] y_train;
wire   [63:0] y_test;
reg    gmem_y_test_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    gmem_y_test_blk_n_W;
wire    ap_CS_fsm_state8;
reg    gmem_y_test_blk_n_B;
wire    ap_CS_fsm_state13;
reg   [63:0] y_train_read_reg_293;
reg   [63:0] X_train_read_reg_298;
reg   [63:0] X_test_read_reg_303;
reg   [63:0] gmem_y_test_addr_reg_326;
reg   [8:0] phi_mul_load_reg_336;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_knn_majority_vote_fu_195_ap_return;
reg   [31:0] tmp_reg_350;
wire    ap_CS_fsm_state7;
wire    grp_knn_distance_and_sort_fu_178_ap_start;
wire    grp_knn_distance_and_sort_fu_178_ap_done;
wire    grp_knn_distance_and_sort_fu_178_ap_idle;
wire    grp_knn_distance_and_sort_fu_178_ap_ready;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWADDR;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWLEN;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWSIZE;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWBURST;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWLOCK;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWCACHE;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWPROT;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWQOS;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWREGION;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WDATA;
wire   [7:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WSTRB;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WLAST;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WID;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARADDR;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARLEN;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARSIZE;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARBURST;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARLOCK;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARCACHE;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARPROT;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARQOS;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARREGION;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_RREADY;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_BREADY;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWADDR;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWLEN;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWSIZE;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWBURST;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWLOCK;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWCACHE;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWPROT;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWQOS;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWREGION;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WDATA;
wire   [7:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WSTRB;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WLAST;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WID;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARADDR;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARLEN;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARSIZE;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARBURST;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARLOCK;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARCACHE;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARPROT;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARQOS;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARREGION;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_RREADY;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_BREADY;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWADDR;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWLEN;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWSIZE;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWBURST;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWLOCK;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWCACHE;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWPROT;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWQOS;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWREGION;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WVALID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WDATA;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WSTRB;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WLAST;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WID;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARVALID;
wire   [63:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARADDR;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARID;
wire   [31:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARLEN;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARSIZE;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARBURST;
wire   [1:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARLOCK;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARCACHE;
wire   [2:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARPROT;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARQOS;
wire   [3:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARREGION;
wire   [0:0] grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARUSER;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_RREADY;
wire    grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_BREADY;
wire   [3:0] grp_knn_distance_and_sort_fu_178_top_k_labels_0;
wire    grp_knn_distance_and_sort_fu_178_top_k_labels_0_ap_vld;
wire   [3:0] grp_knn_distance_and_sort_fu_178_top_k_labels_1;
wire    grp_knn_distance_and_sort_fu_178_top_k_labels_1_ap_vld;
wire   [3:0] grp_knn_distance_and_sort_fu_178_top_k_labels_2;
wire    grp_knn_distance_and_sort_fu_178_top_k_labels_2_ap_vld;
wire    grp_knn_majority_vote_fu_195_ap_start;
wire    grp_knn_majority_vote_fu_195_ap_done;
wire    grp_knn_majority_vote_fu_195_ap_idle;
wire    grp_knn_majority_vote_fu_195_ap_ready;
wire    gmem_x_test_0_AWREADY;
wire    gmem_x_test_0_WREADY;
reg    gmem_x_test_0_ARVALID;
wire    gmem_x_test_0_ARREADY;
wire    gmem_x_test_0_RVALID;
reg    gmem_x_test_0_RREADY;
wire   [63:0] gmem_x_test_0_RDATA;
wire   [8:0] gmem_x_test_0_RFIFONUM;
wire    gmem_x_test_0_BVALID;
wire    gmem_x_train_0_AWREADY;
wire    gmem_x_train_0_WREADY;
reg    gmem_x_train_0_ARVALID;
wire    gmem_x_train_0_ARREADY;
wire    gmem_x_train_0_RVALID;
reg    gmem_x_train_0_RREADY;
wire   [63:0] gmem_x_train_0_RDATA;
wire   [8:0] gmem_x_train_0_RFIFONUM;
wire    gmem_x_train_0_BVALID;
reg    gmem_y_test_0_AWVALID;
wire    gmem_y_test_0_AWREADY;
wire   [31:0] gmem_y_test_0_AWLEN;
reg    gmem_y_test_0_WVALID;
wire    gmem_y_test_0_WREADY;
wire    gmem_y_test_0_ARREADY;
wire    gmem_y_test_0_RVALID;
wire   [31:0] gmem_y_test_0_RDATA;
wire   [8:0] gmem_y_test_0_RFIFONUM;
wire    gmem_y_test_0_BVALID;
reg    gmem_y_test_0_BREADY;
wire    gmem_y_train_0_AWREADY;
wire    gmem_y_train_0_WREADY;
reg    gmem_y_train_0_ARVALID;
wire    gmem_y_train_0_ARREADY;
wire    gmem_y_train_0_RVALID;
reg    gmem_y_train_0_RREADY;
wire   [31:0] gmem_y_train_0_RDATA;
wire   [8:0] gmem_y_train_0_RFIFONUM;
wire    gmem_y_train_0_BVALID;
reg    grp_knn_distance_and_sort_fu_178_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [3:0] top_k_labels_fu_122;
reg   [3:0] top_k_labels_1_fu_126;
reg   [3:0] top_k_labels_2_fu_130;
reg    grp_knn_majority_vote_fu_195_ap_start_reg;
wire    ap_CS_fsm_state6;
wire  signed [63:0] sext_ln160_fu_212_p1;
reg   [8:0] phi_mul_fu_114;
wire   [8:0] add_ln163_fu_256_p2;
reg   [3:0] i_fu_118;
wire   [3:0] add_ln160_fu_241_p2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln160_fu_235_p2;
wire   [61:0] trunc_ln_fu_202_p4;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 grp_knn_distance_and_sort_fu_178_ap_start_reg = 1'b0;
#0 grp_knn_majority_vote_fu_195_ap_start_reg = 1'b0;
#0 phi_mul_fu_114 = 9'd0;
#0 i_fu_118 = 4'd0;
end

knn_accelerator_knn_distance_and_sort grp_knn_distance_and_sort_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_knn_distance_and_sort_fu_178_ap_start),
    .ap_done(grp_knn_distance_and_sort_fu_178_ap_done),
    .ap_idle(grp_knn_distance_and_sort_fu_178_ap_idle),
    .ap_ready(grp_knn_distance_and_sort_fu_178_ap_ready),
    .m_axi_gmem_x_test_0_AWVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWVALID),
    .m_axi_gmem_x_test_0_AWREADY(1'b0),
    .m_axi_gmem_x_test_0_AWADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWADDR),
    .m_axi_gmem_x_test_0_AWID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWID),
    .m_axi_gmem_x_test_0_AWLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWLEN),
    .m_axi_gmem_x_test_0_AWSIZE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWSIZE),
    .m_axi_gmem_x_test_0_AWBURST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWBURST),
    .m_axi_gmem_x_test_0_AWLOCK(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWLOCK),
    .m_axi_gmem_x_test_0_AWCACHE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWCACHE),
    .m_axi_gmem_x_test_0_AWPROT(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWPROT),
    .m_axi_gmem_x_test_0_AWQOS(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWQOS),
    .m_axi_gmem_x_test_0_AWREGION(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWREGION),
    .m_axi_gmem_x_test_0_AWUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_AWUSER),
    .m_axi_gmem_x_test_0_WVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WVALID),
    .m_axi_gmem_x_test_0_WREADY(1'b0),
    .m_axi_gmem_x_test_0_WDATA(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WDATA),
    .m_axi_gmem_x_test_0_WSTRB(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WSTRB),
    .m_axi_gmem_x_test_0_WLAST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WLAST),
    .m_axi_gmem_x_test_0_WID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WID),
    .m_axi_gmem_x_test_0_WUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_WUSER),
    .m_axi_gmem_x_test_0_ARVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARVALID),
    .m_axi_gmem_x_test_0_ARREADY(gmem_x_test_0_ARREADY),
    .m_axi_gmem_x_test_0_ARADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARADDR),
    .m_axi_gmem_x_test_0_ARID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARID),
    .m_axi_gmem_x_test_0_ARLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARLEN),
    .m_axi_gmem_x_test_0_ARSIZE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARSIZE),
    .m_axi_gmem_x_test_0_ARBURST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARBURST),
    .m_axi_gmem_x_test_0_ARLOCK(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARLOCK),
    .m_axi_gmem_x_test_0_ARCACHE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARCACHE),
    .m_axi_gmem_x_test_0_ARPROT(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARPROT),
    .m_axi_gmem_x_test_0_ARQOS(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARQOS),
    .m_axi_gmem_x_test_0_ARREGION(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARREGION),
    .m_axi_gmem_x_test_0_ARUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARUSER),
    .m_axi_gmem_x_test_0_RVALID(gmem_x_test_0_RVALID),
    .m_axi_gmem_x_test_0_RREADY(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_RREADY),
    .m_axi_gmem_x_test_0_RDATA(gmem_x_test_0_RDATA),
    .m_axi_gmem_x_test_0_RLAST(1'b0),
    .m_axi_gmem_x_test_0_RID(1'd0),
    .m_axi_gmem_x_test_0_RFIFONUM(gmem_x_test_0_RFIFONUM),
    .m_axi_gmem_x_test_0_RUSER(1'd0),
    .m_axi_gmem_x_test_0_RRESP(2'd0),
    .m_axi_gmem_x_test_0_BVALID(1'b0),
    .m_axi_gmem_x_test_0_BREADY(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_BREADY),
    .m_axi_gmem_x_test_0_BRESP(2'd0),
    .m_axi_gmem_x_test_0_BID(1'd0),
    .m_axi_gmem_x_test_0_BUSER(1'd0),
    .test_point(X_test_read_reg_303),
    .m_axi_gmem_x_train_0_AWVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWVALID),
    .m_axi_gmem_x_train_0_AWREADY(1'b0),
    .m_axi_gmem_x_train_0_AWADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWADDR),
    .m_axi_gmem_x_train_0_AWID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWID),
    .m_axi_gmem_x_train_0_AWLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWLEN),
    .m_axi_gmem_x_train_0_AWSIZE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWSIZE),
    .m_axi_gmem_x_train_0_AWBURST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWBURST),
    .m_axi_gmem_x_train_0_AWLOCK(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWLOCK),
    .m_axi_gmem_x_train_0_AWCACHE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWCACHE),
    .m_axi_gmem_x_train_0_AWPROT(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWPROT),
    .m_axi_gmem_x_train_0_AWQOS(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWQOS),
    .m_axi_gmem_x_train_0_AWREGION(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWREGION),
    .m_axi_gmem_x_train_0_AWUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_AWUSER),
    .m_axi_gmem_x_train_0_WVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WVALID),
    .m_axi_gmem_x_train_0_WREADY(1'b0),
    .m_axi_gmem_x_train_0_WDATA(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WDATA),
    .m_axi_gmem_x_train_0_WSTRB(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WSTRB),
    .m_axi_gmem_x_train_0_WLAST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WLAST),
    .m_axi_gmem_x_train_0_WID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WID),
    .m_axi_gmem_x_train_0_WUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_WUSER),
    .m_axi_gmem_x_train_0_ARVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARVALID),
    .m_axi_gmem_x_train_0_ARREADY(gmem_x_train_0_ARREADY),
    .m_axi_gmem_x_train_0_ARADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARADDR),
    .m_axi_gmem_x_train_0_ARID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARID),
    .m_axi_gmem_x_train_0_ARLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARLEN),
    .m_axi_gmem_x_train_0_ARSIZE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARSIZE),
    .m_axi_gmem_x_train_0_ARBURST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARBURST),
    .m_axi_gmem_x_train_0_ARLOCK(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARLOCK),
    .m_axi_gmem_x_train_0_ARCACHE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARCACHE),
    .m_axi_gmem_x_train_0_ARPROT(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARPROT),
    .m_axi_gmem_x_train_0_ARQOS(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARQOS),
    .m_axi_gmem_x_train_0_ARREGION(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARREGION),
    .m_axi_gmem_x_train_0_ARUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARUSER),
    .m_axi_gmem_x_train_0_RVALID(gmem_x_train_0_RVALID),
    .m_axi_gmem_x_train_0_RREADY(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_RREADY),
    .m_axi_gmem_x_train_0_RDATA(gmem_x_train_0_RDATA),
    .m_axi_gmem_x_train_0_RLAST(1'b0),
    .m_axi_gmem_x_train_0_RID(1'd0),
    .m_axi_gmem_x_train_0_RFIFONUM(gmem_x_train_0_RFIFONUM),
    .m_axi_gmem_x_train_0_RUSER(1'd0),
    .m_axi_gmem_x_train_0_RRESP(2'd0),
    .m_axi_gmem_x_train_0_BVALID(1'b0),
    .m_axi_gmem_x_train_0_BREADY(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_BREADY),
    .m_axi_gmem_x_train_0_BRESP(2'd0),
    .m_axi_gmem_x_train_0_BID(1'd0),
    .m_axi_gmem_x_train_0_BUSER(1'd0),
    .X_train(X_train_read_reg_298),
    .m_axi_gmem_y_train_0_AWVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWVALID),
    .m_axi_gmem_y_train_0_AWREADY(1'b0),
    .m_axi_gmem_y_train_0_AWADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWADDR),
    .m_axi_gmem_y_train_0_AWID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWID),
    .m_axi_gmem_y_train_0_AWLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWLEN),
    .m_axi_gmem_y_train_0_AWSIZE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWSIZE),
    .m_axi_gmem_y_train_0_AWBURST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWBURST),
    .m_axi_gmem_y_train_0_AWLOCK(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWLOCK),
    .m_axi_gmem_y_train_0_AWCACHE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWCACHE),
    .m_axi_gmem_y_train_0_AWPROT(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWPROT),
    .m_axi_gmem_y_train_0_AWQOS(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWQOS),
    .m_axi_gmem_y_train_0_AWREGION(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWREGION),
    .m_axi_gmem_y_train_0_AWUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_AWUSER),
    .m_axi_gmem_y_train_0_WVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WVALID),
    .m_axi_gmem_y_train_0_WREADY(1'b0),
    .m_axi_gmem_y_train_0_WDATA(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WDATA),
    .m_axi_gmem_y_train_0_WSTRB(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WSTRB),
    .m_axi_gmem_y_train_0_WLAST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WLAST),
    .m_axi_gmem_y_train_0_WID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WID),
    .m_axi_gmem_y_train_0_WUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_WUSER),
    .m_axi_gmem_y_train_0_ARVALID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARVALID),
    .m_axi_gmem_y_train_0_ARREADY(gmem_y_train_0_ARREADY),
    .m_axi_gmem_y_train_0_ARADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARADDR),
    .m_axi_gmem_y_train_0_ARID(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARID),
    .m_axi_gmem_y_train_0_ARLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARLEN),
    .m_axi_gmem_y_train_0_ARSIZE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARSIZE),
    .m_axi_gmem_y_train_0_ARBURST(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARBURST),
    .m_axi_gmem_y_train_0_ARLOCK(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARLOCK),
    .m_axi_gmem_y_train_0_ARCACHE(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARCACHE),
    .m_axi_gmem_y_train_0_ARPROT(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARPROT),
    .m_axi_gmem_y_train_0_ARQOS(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARQOS),
    .m_axi_gmem_y_train_0_ARREGION(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARREGION),
    .m_axi_gmem_y_train_0_ARUSER(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARUSER),
    .m_axi_gmem_y_train_0_RVALID(gmem_y_train_0_RVALID),
    .m_axi_gmem_y_train_0_RREADY(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_RREADY),
    .m_axi_gmem_y_train_0_RDATA(gmem_y_train_0_RDATA),
    .m_axi_gmem_y_train_0_RLAST(1'b0),
    .m_axi_gmem_y_train_0_RID(1'd0),
    .m_axi_gmem_y_train_0_RFIFONUM(gmem_y_train_0_RFIFONUM),
    .m_axi_gmem_y_train_0_RUSER(1'd0),
    .m_axi_gmem_y_train_0_RRESP(2'd0),
    .m_axi_gmem_y_train_0_BVALID(1'b0),
    .m_axi_gmem_y_train_0_BREADY(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_BREADY),
    .m_axi_gmem_y_train_0_BRESP(2'd0),
    .m_axi_gmem_y_train_0_BID(1'd0),
    .m_axi_gmem_y_train_0_BUSER(1'd0),
    .y_train(y_train_read_reg_293),
    .top_k_labels_0(grp_knn_distance_and_sort_fu_178_top_k_labels_0),
    .top_k_labels_0_ap_vld(grp_knn_distance_and_sort_fu_178_top_k_labels_0_ap_vld),
    .top_k_labels_1(grp_knn_distance_and_sort_fu_178_top_k_labels_1),
    .top_k_labels_1_ap_vld(grp_knn_distance_and_sort_fu_178_top_k_labels_1_ap_vld),
    .top_k_labels_2(grp_knn_distance_and_sort_fu_178_top_k_labels_2),
    .top_k_labels_2_ap_vld(grp_knn_distance_and_sort_fu_178_top_k_labels_2_ap_vld),
    .idx(phi_mul_load_reg_336)
);

knn_accelerator_knn_majority_vote grp_knn_majority_vote_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_knn_majority_vote_fu_195_ap_start),
    .ap_done(grp_knn_majority_vote_fu_195_ap_done),
    .ap_idle(grp_knn_majority_vote_fu_195_ap_idle),
    .ap_ready(grp_knn_majority_vote_fu_195_ap_ready),
    .top_k_labels_read(top_k_labels_fu_122),
    .top_k_labels_read_8(top_k_labels_1_fu_126),
    .top_k_labels_read_9(top_k_labels_2_fu_130),
    .ap_return(grp_knn_majority_vote_fu_195_ap_return)
);

knn_accelerator_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

knn_accelerator_control_r_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_R_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_R_DATA_WIDTH ))
control_r_s_axi_U(
    .AWVALID(s_axi_control_r_AWVALID),
    .AWREADY(s_axi_control_r_AWREADY),
    .AWADDR(s_axi_control_r_AWADDR),
    .WVALID(s_axi_control_r_WVALID),
    .WREADY(s_axi_control_r_WREADY),
    .WDATA(s_axi_control_r_WDATA),
    .WSTRB(s_axi_control_r_WSTRB),
    .ARVALID(s_axi_control_r_ARVALID),
    .ARREADY(s_axi_control_r_ARREADY),
    .ARADDR(s_axi_control_r_ARADDR),
    .RVALID(s_axi_control_r_RVALID),
    .RREADY(s_axi_control_r_RREADY),
    .RDATA(s_axi_control_r_RDATA),
    .RRESP(s_axi_control_r_RRESP),
    .BVALID(s_axi_control_r_BVALID),
    .BREADY(s_axi_control_r_BREADY),
    .BRESP(s_axi_control_r_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .X_test(X_test),
    .X_train(X_train),
    .y_train(y_train),
    .y_test(y_test)
);

knn_accelerator_gmem_x_test_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_X_TEST_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_X_TEST_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_X_TEST_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_X_TEST_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_X_TEST_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_X_TEST_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_X_TEST_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_X_TEST_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_X_TEST_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_X_TEST_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_X_TEST_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_x_test_m_axi_U(
    .AWVALID(m_axi_gmem_x_test_AWVALID),
    .AWREADY(m_axi_gmem_x_test_AWREADY),
    .AWADDR(m_axi_gmem_x_test_AWADDR),
    .AWID(m_axi_gmem_x_test_AWID),
    .AWLEN(m_axi_gmem_x_test_AWLEN),
    .AWSIZE(m_axi_gmem_x_test_AWSIZE),
    .AWBURST(m_axi_gmem_x_test_AWBURST),
    .AWLOCK(m_axi_gmem_x_test_AWLOCK),
    .AWCACHE(m_axi_gmem_x_test_AWCACHE),
    .AWPROT(m_axi_gmem_x_test_AWPROT),
    .AWQOS(m_axi_gmem_x_test_AWQOS),
    .AWREGION(m_axi_gmem_x_test_AWREGION),
    .AWUSER(m_axi_gmem_x_test_AWUSER),
    .WVALID(m_axi_gmem_x_test_WVALID),
    .WREADY(m_axi_gmem_x_test_WREADY),
    .WDATA(m_axi_gmem_x_test_WDATA),
    .WSTRB(m_axi_gmem_x_test_WSTRB),
    .WLAST(m_axi_gmem_x_test_WLAST),
    .WID(m_axi_gmem_x_test_WID),
    .WUSER(m_axi_gmem_x_test_WUSER),
    .ARVALID(m_axi_gmem_x_test_ARVALID),
    .ARREADY(m_axi_gmem_x_test_ARREADY),
    .ARADDR(m_axi_gmem_x_test_ARADDR),
    .ARID(m_axi_gmem_x_test_ARID),
    .ARLEN(m_axi_gmem_x_test_ARLEN),
    .ARSIZE(m_axi_gmem_x_test_ARSIZE),
    .ARBURST(m_axi_gmem_x_test_ARBURST),
    .ARLOCK(m_axi_gmem_x_test_ARLOCK),
    .ARCACHE(m_axi_gmem_x_test_ARCACHE),
    .ARPROT(m_axi_gmem_x_test_ARPROT),
    .ARQOS(m_axi_gmem_x_test_ARQOS),
    .ARREGION(m_axi_gmem_x_test_ARREGION),
    .ARUSER(m_axi_gmem_x_test_ARUSER),
    .RVALID(m_axi_gmem_x_test_RVALID),
    .RREADY(m_axi_gmem_x_test_RREADY),
    .RDATA(m_axi_gmem_x_test_RDATA),
    .RLAST(m_axi_gmem_x_test_RLAST),
    .RID(m_axi_gmem_x_test_RID),
    .RUSER(m_axi_gmem_x_test_RUSER),
    .RRESP(m_axi_gmem_x_test_RRESP),
    .BVALID(m_axi_gmem_x_test_BVALID),
    .BREADY(m_axi_gmem_x_test_BREADY),
    .BRESP(m_axi_gmem_x_test_BRESP),
    .BID(m_axi_gmem_x_test_BID),
    .BUSER(m_axi_gmem_x_test_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_x_test_0_ARVALID),
    .I_CH0_ARREADY(gmem_x_test_0_ARREADY),
    .I_CH0_ARADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARADDR),
    .I_CH0_ARLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARLEN),
    .I_CH0_RVALID(gmem_x_test_0_RVALID),
    .I_CH0_RREADY(gmem_x_test_0_RREADY),
    .I_CH0_RDATA(gmem_x_test_0_RDATA),
    .I_CH0_RFIFONUM(gmem_x_test_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_x_test_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_x_test_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(gmem_x_test_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

knn_accelerator_gmem_x_train_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_X_TRAIN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_X_TRAIN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_X_TRAIN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_X_TRAIN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_X_TRAIN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_X_TRAIN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_X_TRAIN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_X_TRAIN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_X_TRAIN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_X_TRAIN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_X_TRAIN_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_x_train_m_axi_U(
    .AWVALID(m_axi_gmem_x_train_AWVALID),
    .AWREADY(m_axi_gmem_x_train_AWREADY),
    .AWADDR(m_axi_gmem_x_train_AWADDR),
    .AWID(m_axi_gmem_x_train_AWID),
    .AWLEN(m_axi_gmem_x_train_AWLEN),
    .AWSIZE(m_axi_gmem_x_train_AWSIZE),
    .AWBURST(m_axi_gmem_x_train_AWBURST),
    .AWLOCK(m_axi_gmem_x_train_AWLOCK),
    .AWCACHE(m_axi_gmem_x_train_AWCACHE),
    .AWPROT(m_axi_gmem_x_train_AWPROT),
    .AWQOS(m_axi_gmem_x_train_AWQOS),
    .AWREGION(m_axi_gmem_x_train_AWREGION),
    .AWUSER(m_axi_gmem_x_train_AWUSER),
    .WVALID(m_axi_gmem_x_train_WVALID),
    .WREADY(m_axi_gmem_x_train_WREADY),
    .WDATA(m_axi_gmem_x_train_WDATA),
    .WSTRB(m_axi_gmem_x_train_WSTRB),
    .WLAST(m_axi_gmem_x_train_WLAST),
    .WID(m_axi_gmem_x_train_WID),
    .WUSER(m_axi_gmem_x_train_WUSER),
    .ARVALID(m_axi_gmem_x_train_ARVALID),
    .ARREADY(m_axi_gmem_x_train_ARREADY),
    .ARADDR(m_axi_gmem_x_train_ARADDR),
    .ARID(m_axi_gmem_x_train_ARID),
    .ARLEN(m_axi_gmem_x_train_ARLEN),
    .ARSIZE(m_axi_gmem_x_train_ARSIZE),
    .ARBURST(m_axi_gmem_x_train_ARBURST),
    .ARLOCK(m_axi_gmem_x_train_ARLOCK),
    .ARCACHE(m_axi_gmem_x_train_ARCACHE),
    .ARPROT(m_axi_gmem_x_train_ARPROT),
    .ARQOS(m_axi_gmem_x_train_ARQOS),
    .ARREGION(m_axi_gmem_x_train_ARREGION),
    .ARUSER(m_axi_gmem_x_train_ARUSER),
    .RVALID(m_axi_gmem_x_train_RVALID),
    .RREADY(m_axi_gmem_x_train_RREADY),
    .RDATA(m_axi_gmem_x_train_RDATA),
    .RLAST(m_axi_gmem_x_train_RLAST),
    .RID(m_axi_gmem_x_train_RID),
    .RUSER(m_axi_gmem_x_train_RUSER),
    .RRESP(m_axi_gmem_x_train_RRESP),
    .BVALID(m_axi_gmem_x_train_BVALID),
    .BREADY(m_axi_gmem_x_train_BREADY),
    .BRESP(m_axi_gmem_x_train_BRESP),
    .BID(m_axi_gmem_x_train_BID),
    .BUSER(m_axi_gmem_x_train_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_x_train_0_ARVALID),
    .I_CH0_ARREADY(gmem_x_train_0_ARREADY),
    .I_CH0_ARADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARADDR),
    .I_CH0_ARLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARLEN),
    .I_CH0_RVALID(gmem_x_train_0_RVALID),
    .I_CH0_RREADY(gmem_x_train_0_RREADY),
    .I_CH0_RDATA(gmem_x_train_0_RDATA),
    .I_CH0_RFIFONUM(gmem_x_train_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_x_train_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_x_train_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(gmem_x_train_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

knn_accelerator_gmem_y_test_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_Y_TEST_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_Y_TEST_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_Y_TEST_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_Y_TEST_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_Y_TEST_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_Y_TEST_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_Y_TEST_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_Y_TEST_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_Y_TEST_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_Y_TEST_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_Y_TEST_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_y_test_m_axi_U(
    .AWVALID(m_axi_gmem_y_test_AWVALID),
    .AWREADY(m_axi_gmem_y_test_AWREADY),
    .AWADDR(m_axi_gmem_y_test_AWADDR),
    .AWID(m_axi_gmem_y_test_AWID),
    .AWLEN(m_axi_gmem_y_test_AWLEN),
    .AWSIZE(m_axi_gmem_y_test_AWSIZE),
    .AWBURST(m_axi_gmem_y_test_AWBURST),
    .AWLOCK(m_axi_gmem_y_test_AWLOCK),
    .AWCACHE(m_axi_gmem_y_test_AWCACHE),
    .AWPROT(m_axi_gmem_y_test_AWPROT),
    .AWQOS(m_axi_gmem_y_test_AWQOS),
    .AWREGION(m_axi_gmem_y_test_AWREGION),
    .AWUSER(m_axi_gmem_y_test_AWUSER),
    .WVALID(m_axi_gmem_y_test_WVALID),
    .WREADY(m_axi_gmem_y_test_WREADY),
    .WDATA(m_axi_gmem_y_test_WDATA),
    .WSTRB(m_axi_gmem_y_test_WSTRB),
    .WLAST(m_axi_gmem_y_test_WLAST),
    .WID(m_axi_gmem_y_test_WID),
    .WUSER(m_axi_gmem_y_test_WUSER),
    .ARVALID(m_axi_gmem_y_test_ARVALID),
    .ARREADY(m_axi_gmem_y_test_ARREADY),
    .ARADDR(m_axi_gmem_y_test_ARADDR),
    .ARID(m_axi_gmem_y_test_ARID),
    .ARLEN(m_axi_gmem_y_test_ARLEN),
    .ARSIZE(m_axi_gmem_y_test_ARSIZE),
    .ARBURST(m_axi_gmem_y_test_ARBURST),
    .ARLOCK(m_axi_gmem_y_test_ARLOCK),
    .ARCACHE(m_axi_gmem_y_test_ARCACHE),
    .ARPROT(m_axi_gmem_y_test_ARPROT),
    .ARQOS(m_axi_gmem_y_test_ARQOS),
    .ARREGION(m_axi_gmem_y_test_ARREGION),
    .ARUSER(m_axi_gmem_y_test_ARUSER),
    .RVALID(m_axi_gmem_y_test_RVALID),
    .RREADY(m_axi_gmem_y_test_RREADY),
    .RDATA(m_axi_gmem_y_test_RDATA),
    .RLAST(m_axi_gmem_y_test_RLAST),
    .RID(m_axi_gmem_y_test_RID),
    .RUSER(m_axi_gmem_y_test_RUSER),
    .RRESP(m_axi_gmem_y_test_RRESP),
    .BVALID(m_axi_gmem_y_test_BVALID),
    .BREADY(m_axi_gmem_y_test_BREADY),
    .BRESP(m_axi_gmem_y_test_BRESP),
    .BID(m_axi_gmem_y_test_BID),
    .BUSER(m_axi_gmem_y_test_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_y_test_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_y_test_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_y_test_0_RDATA),
    .I_CH0_RFIFONUM(gmem_y_test_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_y_test_0_AWVALID),
    .I_CH0_AWREADY(gmem_y_test_0_AWREADY),
    .I_CH0_AWADDR(gmem_y_test_addr_reg_326),
    .I_CH0_AWLEN(gmem_y_test_0_AWLEN),
    .I_CH0_WVALID(gmem_y_test_0_WVALID),
    .I_CH0_WREADY(gmem_y_test_0_WREADY),
    .I_CH0_WDATA(tmp_reg_350),
    .I_CH0_WSTRB(4'd15),
    .I_CH0_BVALID(gmem_y_test_0_BVALID),
    .I_CH0_BREADY(gmem_y_test_0_BREADY)
);

knn_accelerator_gmem_y_train_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_Y_TRAIN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_Y_TRAIN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_Y_TRAIN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_Y_TRAIN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_Y_TRAIN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_Y_TRAIN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_Y_TRAIN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_Y_TRAIN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_Y_TRAIN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_Y_TRAIN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_Y_TRAIN_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_y_train_m_axi_U(
    .AWVALID(m_axi_gmem_y_train_AWVALID),
    .AWREADY(m_axi_gmem_y_train_AWREADY),
    .AWADDR(m_axi_gmem_y_train_AWADDR),
    .AWID(m_axi_gmem_y_train_AWID),
    .AWLEN(m_axi_gmem_y_train_AWLEN),
    .AWSIZE(m_axi_gmem_y_train_AWSIZE),
    .AWBURST(m_axi_gmem_y_train_AWBURST),
    .AWLOCK(m_axi_gmem_y_train_AWLOCK),
    .AWCACHE(m_axi_gmem_y_train_AWCACHE),
    .AWPROT(m_axi_gmem_y_train_AWPROT),
    .AWQOS(m_axi_gmem_y_train_AWQOS),
    .AWREGION(m_axi_gmem_y_train_AWREGION),
    .AWUSER(m_axi_gmem_y_train_AWUSER),
    .WVALID(m_axi_gmem_y_train_WVALID),
    .WREADY(m_axi_gmem_y_train_WREADY),
    .WDATA(m_axi_gmem_y_train_WDATA),
    .WSTRB(m_axi_gmem_y_train_WSTRB),
    .WLAST(m_axi_gmem_y_train_WLAST),
    .WID(m_axi_gmem_y_train_WID),
    .WUSER(m_axi_gmem_y_train_WUSER),
    .ARVALID(m_axi_gmem_y_train_ARVALID),
    .ARREADY(m_axi_gmem_y_train_ARREADY),
    .ARADDR(m_axi_gmem_y_train_ARADDR),
    .ARID(m_axi_gmem_y_train_ARID),
    .ARLEN(m_axi_gmem_y_train_ARLEN),
    .ARSIZE(m_axi_gmem_y_train_ARSIZE),
    .ARBURST(m_axi_gmem_y_train_ARBURST),
    .ARLOCK(m_axi_gmem_y_train_ARLOCK),
    .ARCACHE(m_axi_gmem_y_train_ARCACHE),
    .ARPROT(m_axi_gmem_y_train_ARPROT),
    .ARQOS(m_axi_gmem_y_train_ARQOS),
    .ARREGION(m_axi_gmem_y_train_ARREGION),
    .ARUSER(m_axi_gmem_y_train_ARUSER),
    .RVALID(m_axi_gmem_y_train_RVALID),
    .RREADY(m_axi_gmem_y_train_RREADY),
    .RDATA(m_axi_gmem_y_train_RDATA),
    .RLAST(m_axi_gmem_y_train_RLAST),
    .RID(m_axi_gmem_y_train_RID),
    .RUSER(m_axi_gmem_y_train_RUSER),
    .RRESP(m_axi_gmem_y_train_RRESP),
    .BVALID(m_axi_gmem_y_train_BVALID),
    .BREADY(m_axi_gmem_y_train_BREADY),
    .BRESP(m_axi_gmem_y_train_BRESP),
    .BID(m_axi_gmem_y_train_BID),
    .BUSER(m_axi_gmem_y_train_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_y_train_0_ARVALID),
    .I_CH0_ARREADY(gmem_y_train_0_ARREADY),
    .I_CH0_ARADDR(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARADDR),
    .I_CH0_ARLEN(grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARLEN),
    .I_CH0_RVALID(gmem_y_train_0_RVALID),
    .I_CH0_RREADY(gmem_y_train_0_RREADY),
    .I_CH0_RDATA(gmem_y_train_0_RDATA),
    .I_CH0_RFIFONUM(gmem_y_train_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_y_train_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_y_train_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem_y_train_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_knn_distance_and_sort_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_knn_distance_and_sort_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_knn_distance_and_sort_fu_178_ap_ready == 1'b1)) begin
            grp_knn_distance_and_sort_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_knn_majority_vote_fu_195_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_knn_majority_vote_fu_195_ap_start_reg <= 1'b1;
        end else if ((grp_knn_majority_vote_fu_195_ap_ready == 1'b1)) begin
            grp_knn_majority_vote_fu_195_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_118 <= 4'd0;
    end else if (((icmp_ln160_fu_235_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_118 <= add_ln160_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_114 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        phi_mul_fu_114 <= add_ln163_fu_256_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        X_test_read_reg_303 <= X_test;
        X_train_read_reg_298 <= X_train;
        gmem_y_test_addr_reg_326 <= sext_ln160_fu_212_p1;
        y_train_read_reg_293 <= y_train;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        phi_mul_load_reg_336 <= phi_mul_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_reg_350 <= grp_knn_majority_vote_fu_195_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_distance_and_sort_fu_178_top_k_labels_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        top_k_labels_1_fu_126 <= grp_knn_distance_and_sort_fu_178_top_k_labels_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_distance_and_sort_fu_178_top_k_labels_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        top_k_labels_2_fu_130 <= grp_knn_distance_and_sort_fu_178_top_k_labels_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_distance_and_sort_fu_178_top_k_labels_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        top_k_labels_fu_122 <= grp_knn_distance_and_sort_fu_178_top_k_labels_0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((gmem_y_test_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_y_test_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_distance_and_sort_fu_178_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_majority_vote_fu_195_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_y_test_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem_y_test_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_y_test_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_x_test_0_ARVALID = grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_ARVALID;
    end else begin
        gmem_x_test_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_x_test_0_RREADY = grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_test_0_RREADY;
    end else begin
        gmem_x_test_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_x_train_0_ARVALID = grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_ARVALID;
    end else begin
        gmem_x_train_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_x_train_0_RREADY = grp_knn_distance_and_sort_fu_178_m_axi_gmem_x_train_0_RREADY;
    end else begin
        gmem_x_train_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_y_test_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_y_test_0_AWVALID = 1'b1;
    end else begin
        gmem_y_test_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_y_test_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        gmem_y_test_0_BREADY = 1'b1;
    end else begin
        gmem_y_test_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_y_test_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem_y_test_0_WVALID = 1'b1;
    end else begin
        gmem_y_test_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_y_test_blk_n_AW = m_axi_gmem_y_test_AWREADY;
    end else begin
        gmem_y_test_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem_y_test_blk_n_B = m_axi_gmem_y_test_BVALID;
    end else begin
        gmem_y_test_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem_y_test_blk_n_W = m_axi_gmem_y_test_WREADY;
    end else begin
        gmem_y_test_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_y_train_0_ARVALID = grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_ARVALID;
    end else begin
        gmem_y_train_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_y_train_0_RREADY = grp_knn_distance_and_sort_fu_178_m_axi_gmem_y_train_0_RREADY;
    end else begin
        gmem_y_train_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_y_test_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln160_fu_235_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_knn_distance_and_sort_fu_178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_knn_majority_vote_fu_195_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((gmem_y_test_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((gmem_y_test_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_241_p2 = (i_fu_118 + 4'd1);

assign add_ln163_fu_256_p2 = (phi_mul_fu_114 + 9'd49);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign gmem_y_test_0_AWLEN = 64'd10;

assign grp_knn_distance_and_sort_fu_178_ap_start = grp_knn_distance_and_sort_fu_178_ap_start_reg;

assign grp_knn_majority_vote_fu_195_ap_start = grp_knn_majority_vote_fu_195_ap_start_reg;

assign icmp_ln160_fu_235_p2 = ((i_fu_118 == 4'd10) ? 1'b1 : 1'b0);

assign sext_ln160_fu_212_p1 = $signed(trunc_ln_fu_202_p4);

assign trunc_ln_fu_202_p4 = {{y_test[63:2]}};

endmodule //knn_accelerator
