// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module knn_accelerator_knn_distance_and_sort (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_x_test_0_AWVALID,
        m_axi_gmem_x_test_0_AWREADY,
        m_axi_gmem_x_test_0_AWADDR,
        m_axi_gmem_x_test_0_AWID,
        m_axi_gmem_x_test_0_AWLEN,
        m_axi_gmem_x_test_0_AWSIZE,
        m_axi_gmem_x_test_0_AWBURST,
        m_axi_gmem_x_test_0_AWLOCK,
        m_axi_gmem_x_test_0_AWCACHE,
        m_axi_gmem_x_test_0_AWPROT,
        m_axi_gmem_x_test_0_AWQOS,
        m_axi_gmem_x_test_0_AWREGION,
        m_axi_gmem_x_test_0_AWUSER,
        m_axi_gmem_x_test_0_WVALID,
        m_axi_gmem_x_test_0_WREADY,
        m_axi_gmem_x_test_0_WDATA,
        m_axi_gmem_x_test_0_WSTRB,
        m_axi_gmem_x_test_0_WLAST,
        m_axi_gmem_x_test_0_WID,
        m_axi_gmem_x_test_0_WUSER,
        m_axi_gmem_x_test_0_ARVALID,
        m_axi_gmem_x_test_0_ARREADY,
        m_axi_gmem_x_test_0_ARADDR,
        m_axi_gmem_x_test_0_ARID,
        m_axi_gmem_x_test_0_ARLEN,
        m_axi_gmem_x_test_0_ARSIZE,
        m_axi_gmem_x_test_0_ARBURST,
        m_axi_gmem_x_test_0_ARLOCK,
        m_axi_gmem_x_test_0_ARCACHE,
        m_axi_gmem_x_test_0_ARPROT,
        m_axi_gmem_x_test_0_ARQOS,
        m_axi_gmem_x_test_0_ARREGION,
        m_axi_gmem_x_test_0_ARUSER,
        m_axi_gmem_x_test_0_RVALID,
        m_axi_gmem_x_test_0_RREADY,
        m_axi_gmem_x_test_0_RDATA,
        m_axi_gmem_x_test_0_RLAST,
        m_axi_gmem_x_test_0_RID,
        m_axi_gmem_x_test_0_RFIFONUM,
        m_axi_gmem_x_test_0_RUSER,
        m_axi_gmem_x_test_0_RRESP,
        m_axi_gmem_x_test_0_BVALID,
        m_axi_gmem_x_test_0_BREADY,
        m_axi_gmem_x_test_0_BRESP,
        m_axi_gmem_x_test_0_BID,
        m_axi_gmem_x_test_0_BUSER,
        test_point,
        m_axi_gmem_x_train_0_AWVALID,
        m_axi_gmem_x_train_0_AWREADY,
        m_axi_gmem_x_train_0_AWADDR,
        m_axi_gmem_x_train_0_AWID,
        m_axi_gmem_x_train_0_AWLEN,
        m_axi_gmem_x_train_0_AWSIZE,
        m_axi_gmem_x_train_0_AWBURST,
        m_axi_gmem_x_train_0_AWLOCK,
        m_axi_gmem_x_train_0_AWCACHE,
        m_axi_gmem_x_train_0_AWPROT,
        m_axi_gmem_x_train_0_AWQOS,
        m_axi_gmem_x_train_0_AWREGION,
        m_axi_gmem_x_train_0_AWUSER,
        m_axi_gmem_x_train_0_WVALID,
        m_axi_gmem_x_train_0_WREADY,
        m_axi_gmem_x_train_0_WDATA,
        m_axi_gmem_x_train_0_WSTRB,
        m_axi_gmem_x_train_0_WLAST,
        m_axi_gmem_x_train_0_WID,
        m_axi_gmem_x_train_0_WUSER,
        m_axi_gmem_x_train_0_ARVALID,
        m_axi_gmem_x_train_0_ARREADY,
        m_axi_gmem_x_train_0_ARADDR,
        m_axi_gmem_x_train_0_ARID,
        m_axi_gmem_x_train_0_ARLEN,
        m_axi_gmem_x_train_0_ARSIZE,
        m_axi_gmem_x_train_0_ARBURST,
        m_axi_gmem_x_train_0_ARLOCK,
        m_axi_gmem_x_train_0_ARCACHE,
        m_axi_gmem_x_train_0_ARPROT,
        m_axi_gmem_x_train_0_ARQOS,
        m_axi_gmem_x_train_0_ARREGION,
        m_axi_gmem_x_train_0_ARUSER,
        m_axi_gmem_x_train_0_RVALID,
        m_axi_gmem_x_train_0_RREADY,
        m_axi_gmem_x_train_0_RDATA,
        m_axi_gmem_x_train_0_RLAST,
        m_axi_gmem_x_train_0_RID,
        m_axi_gmem_x_train_0_RFIFONUM,
        m_axi_gmem_x_train_0_RUSER,
        m_axi_gmem_x_train_0_RRESP,
        m_axi_gmem_x_train_0_BVALID,
        m_axi_gmem_x_train_0_BREADY,
        m_axi_gmem_x_train_0_BRESP,
        m_axi_gmem_x_train_0_BID,
        m_axi_gmem_x_train_0_BUSER,
        X_train,
        m_axi_gmem_y_train_0_AWVALID,
        m_axi_gmem_y_train_0_AWREADY,
        m_axi_gmem_y_train_0_AWADDR,
        m_axi_gmem_y_train_0_AWID,
        m_axi_gmem_y_train_0_AWLEN,
        m_axi_gmem_y_train_0_AWSIZE,
        m_axi_gmem_y_train_0_AWBURST,
        m_axi_gmem_y_train_0_AWLOCK,
        m_axi_gmem_y_train_0_AWCACHE,
        m_axi_gmem_y_train_0_AWPROT,
        m_axi_gmem_y_train_0_AWQOS,
        m_axi_gmem_y_train_0_AWREGION,
        m_axi_gmem_y_train_0_AWUSER,
        m_axi_gmem_y_train_0_WVALID,
        m_axi_gmem_y_train_0_WREADY,
        m_axi_gmem_y_train_0_WDATA,
        m_axi_gmem_y_train_0_WSTRB,
        m_axi_gmem_y_train_0_WLAST,
        m_axi_gmem_y_train_0_WID,
        m_axi_gmem_y_train_0_WUSER,
        m_axi_gmem_y_train_0_ARVALID,
        m_axi_gmem_y_train_0_ARREADY,
        m_axi_gmem_y_train_0_ARADDR,
        m_axi_gmem_y_train_0_ARID,
        m_axi_gmem_y_train_0_ARLEN,
        m_axi_gmem_y_train_0_ARSIZE,
        m_axi_gmem_y_train_0_ARBURST,
        m_axi_gmem_y_train_0_ARLOCK,
        m_axi_gmem_y_train_0_ARCACHE,
        m_axi_gmem_y_train_0_ARPROT,
        m_axi_gmem_y_train_0_ARQOS,
        m_axi_gmem_y_train_0_ARREGION,
        m_axi_gmem_y_train_0_ARUSER,
        m_axi_gmem_y_train_0_RVALID,
        m_axi_gmem_y_train_0_RREADY,
        m_axi_gmem_y_train_0_RDATA,
        m_axi_gmem_y_train_0_RLAST,
        m_axi_gmem_y_train_0_RID,
        m_axi_gmem_y_train_0_RFIFONUM,
        m_axi_gmem_y_train_0_RUSER,
        m_axi_gmem_y_train_0_RRESP,
        m_axi_gmem_y_train_0_BVALID,
        m_axi_gmem_y_train_0_BREADY,
        m_axi_gmem_y_train_0_BRESP,
        m_axi_gmem_y_train_0_BID,
        m_axi_gmem_y_train_0_BUSER,
        y_train,
        top_k_labels_0,
        top_k_labels_0_ap_vld,
        top_k_labels_1,
        top_k_labels_1_ap_vld,
        top_k_labels_2,
        top_k_labels_2_ap_vld,
        idx
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_x_test_0_AWVALID;
input   m_axi_gmem_x_test_0_AWREADY;
output  [63:0] m_axi_gmem_x_test_0_AWADDR;
output  [0:0] m_axi_gmem_x_test_0_AWID;
output  [31:0] m_axi_gmem_x_test_0_AWLEN;
output  [2:0] m_axi_gmem_x_test_0_AWSIZE;
output  [1:0] m_axi_gmem_x_test_0_AWBURST;
output  [1:0] m_axi_gmem_x_test_0_AWLOCK;
output  [3:0] m_axi_gmem_x_test_0_AWCACHE;
output  [2:0] m_axi_gmem_x_test_0_AWPROT;
output  [3:0] m_axi_gmem_x_test_0_AWQOS;
output  [3:0] m_axi_gmem_x_test_0_AWREGION;
output  [0:0] m_axi_gmem_x_test_0_AWUSER;
output   m_axi_gmem_x_test_0_WVALID;
input   m_axi_gmem_x_test_0_WREADY;
output  [63:0] m_axi_gmem_x_test_0_WDATA;
output  [7:0] m_axi_gmem_x_test_0_WSTRB;
output   m_axi_gmem_x_test_0_WLAST;
output  [0:0] m_axi_gmem_x_test_0_WID;
output  [0:0] m_axi_gmem_x_test_0_WUSER;
output   m_axi_gmem_x_test_0_ARVALID;
input   m_axi_gmem_x_test_0_ARREADY;
output  [63:0] m_axi_gmem_x_test_0_ARADDR;
output  [0:0] m_axi_gmem_x_test_0_ARID;
output  [31:0] m_axi_gmem_x_test_0_ARLEN;
output  [2:0] m_axi_gmem_x_test_0_ARSIZE;
output  [1:0] m_axi_gmem_x_test_0_ARBURST;
output  [1:0] m_axi_gmem_x_test_0_ARLOCK;
output  [3:0] m_axi_gmem_x_test_0_ARCACHE;
output  [2:0] m_axi_gmem_x_test_0_ARPROT;
output  [3:0] m_axi_gmem_x_test_0_ARQOS;
output  [3:0] m_axi_gmem_x_test_0_ARREGION;
output  [0:0] m_axi_gmem_x_test_0_ARUSER;
input   m_axi_gmem_x_test_0_RVALID;
output   m_axi_gmem_x_test_0_RREADY;
input  [63:0] m_axi_gmem_x_test_0_RDATA;
input   m_axi_gmem_x_test_0_RLAST;
input  [0:0] m_axi_gmem_x_test_0_RID;
input  [8:0] m_axi_gmem_x_test_0_RFIFONUM;
input  [0:0] m_axi_gmem_x_test_0_RUSER;
input  [1:0] m_axi_gmem_x_test_0_RRESP;
input   m_axi_gmem_x_test_0_BVALID;
output   m_axi_gmem_x_test_0_BREADY;
input  [1:0] m_axi_gmem_x_test_0_BRESP;
input  [0:0] m_axi_gmem_x_test_0_BID;
input  [0:0] m_axi_gmem_x_test_0_BUSER;
input  [63:0] test_point;
output   m_axi_gmem_x_train_0_AWVALID;
input   m_axi_gmem_x_train_0_AWREADY;
output  [63:0] m_axi_gmem_x_train_0_AWADDR;
output  [0:0] m_axi_gmem_x_train_0_AWID;
output  [31:0] m_axi_gmem_x_train_0_AWLEN;
output  [2:0] m_axi_gmem_x_train_0_AWSIZE;
output  [1:0] m_axi_gmem_x_train_0_AWBURST;
output  [1:0] m_axi_gmem_x_train_0_AWLOCK;
output  [3:0] m_axi_gmem_x_train_0_AWCACHE;
output  [2:0] m_axi_gmem_x_train_0_AWPROT;
output  [3:0] m_axi_gmem_x_train_0_AWQOS;
output  [3:0] m_axi_gmem_x_train_0_AWREGION;
output  [0:0] m_axi_gmem_x_train_0_AWUSER;
output   m_axi_gmem_x_train_0_WVALID;
input   m_axi_gmem_x_train_0_WREADY;
output  [63:0] m_axi_gmem_x_train_0_WDATA;
output  [7:0] m_axi_gmem_x_train_0_WSTRB;
output   m_axi_gmem_x_train_0_WLAST;
output  [0:0] m_axi_gmem_x_train_0_WID;
output  [0:0] m_axi_gmem_x_train_0_WUSER;
output   m_axi_gmem_x_train_0_ARVALID;
input   m_axi_gmem_x_train_0_ARREADY;
output  [63:0] m_axi_gmem_x_train_0_ARADDR;
output  [0:0] m_axi_gmem_x_train_0_ARID;
output  [31:0] m_axi_gmem_x_train_0_ARLEN;
output  [2:0] m_axi_gmem_x_train_0_ARSIZE;
output  [1:0] m_axi_gmem_x_train_0_ARBURST;
output  [1:0] m_axi_gmem_x_train_0_ARLOCK;
output  [3:0] m_axi_gmem_x_train_0_ARCACHE;
output  [2:0] m_axi_gmem_x_train_0_ARPROT;
output  [3:0] m_axi_gmem_x_train_0_ARQOS;
output  [3:0] m_axi_gmem_x_train_0_ARREGION;
output  [0:0] m_axi_gmem_x_train_0_ARUSER;
input   m_axi_gmem_x_train_0_RVALID;
output   m_axi_gmem_x_train_0_RREADY;
input  [63:0] m_axi_gmem_x_train_0_RDATA;
input   m_axi_gmem_x_train_0_RLAST;
input  [0:0] m_axi_gmem_x_train_0_RID;
input  [8:0] m_axi_gmem_x_train_0_RFIFONUM;
input  [0:0] m_axi_gmem_x_train_0_RUSER;
input  [1:0] m_axi_gmem_x_train_0_RRESP;
input   m_axi_gmem_x_train_0_BVALID;
output   m_axi_gmem_x_train_0_BREADY;
input  [1:0] m_axi_gmem_x_train_0_BRESP;
input  [0:0] m_axi_gmem_x_train_0_BID;
input  [0:0] m_axi_gmem_x_train_0_BUSER;
input  [63:0] X_train;
output   m_axi_gmem_y_train_0_AWVALID;
input   m_axi_gmem_y_train_0_AWREADY;
output  [63:0] m_axi_gmem_y_train_0_AWADDR;
output  [0:0] m_axi_gmem_y_train_0_AWID;
output  [31:0] m_axi_gmem_y_train_0_AWLEN;
output  [2:0] m_axi_gmem_y_train_0_AWSIZE;
output  [1:0] m_axi_gmem_y_train_0_AWBURST;
output  [1:0] m_axi_gmem_y_train_0_AWLOCK;
output  [3:0] m_axi_gmem_y_train_0_AWCACHE;
output  [2:0] m_axi_gmem_y_train_0_AWPROT;
output  [3:0] m_axi_gmem_y_train_0_AWQOS;
output  [3:0] m_axi_gmem_y_train_0_AWREGION;
output  [0:0] m_axi_gmem_y_train_0_AWUSER;
output   m_axi_gmem_y_train_0_WVALID;
input   m_axi_gmem_y_train_0_WREADY;
output  [31:0] m_axi_gmem_y_train_0_WDATA;
output  [3:0] m_axi_gmem_y_train_0_WSTRB;
output   m_axi_gmem_y_train_0_WLAST;
output  [0:0] m_axi_gmem_y_train_0_WID;
output  [0:0] m_axi_gmem_y_train_0_WUSER;
output   m_axi_gmem_y_train_0_ARVALID;
input   m_axi_gmem_y_train_0_ARREADY;
output  [63:0] m_axi_gmem_y_train_0_ARADDR;
output  [0:0] m_axi_gmem_y_train_0_ARID;
output  [31:0] m_axi_gmem_y_train_0_ARLEN;
output  [2:0] m_axi_gmem_y_train_0_ARSIZE;
output  [1:0] m_axi_gmem_y_train_0_ARBURST;
output  [1:0] m_axi_gmem_y_train_0_ARLOCK;
output  [3:0] m_axi_gmem_y_train_0_ARCACHE;
output  [2:0] m_axi_gmem_y_train_0_ARPROT;
output  [3:0] m_axi_gmem_y_train_0_ARQOS;
output  [3:0] m_axi_gmem_y_train_0_ARREGION;
output  [0:0] m_axi_gmem_y_train_0_ARUSER;
input   m_axi_gmem_y_train_0_RVALID;
output   m_axi_gmem_y_train_0_RREADY;
input  [31:0] m_axi_gmem_y_train_0_RDATA;
input   m_axi_gmem_y_train_0_RLAST;
input  [0:0] m_axi_gmem_y_train_0_RID;
input  [8:0] m_axi_gmem_y_train_0_RFIFONUM;
input  [0:0] m_axi_gmem_y_train_0_RUSER;
input  [1:0] m_axi_gmem_y_train_0_RRESP;
input   m_axi_gmem_y_train_0_BVALID;
output   m_axi_gmem_y_train_0_BREADY;
input  [1:0] m_axi_gmem_y_train_0_BRESP;
input  [0:0] m_axi_gmem_y_train_0_BID;
input  [0:0] m_axi_gmem_y_train_0_BUSER;
input  [63:0] y_train;
output  [3:0] top_k_labels_0;
output   top_k_labels_0_ap_vld;
output  [3:0] top_k_labels_1;
output   top_k_labels_1_ap_vld;
output  [3:0] top_k_labels_2;
output   top_k_labels_2_ap_vld;
input  [8:0] idx;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_x_train_0_ARVALID;
reg[63:0] m_axi_gmem_x_train_0_ARADDR;
reg[0:0] m_axi_gmem_x_train_0_ARID;
reg[31:0] m_axi_gmem_x_train_0_ARLEN;
reg[2:0] m_axi_gmem_x_train_0_ARSIZE;
reg[1:0] m_axi_gmem_x_train_0_ARBURST;
reg[1:0] m_axi_gmem_x_train_0_ARLOCK;
reg[3:0] m_axi_gmem_x_train_0_ARCACHE;
reg[2:0] m_axi_gmem_x_train_0_ARPROT;
reg[3:0] m_axi_gmem_x_train_0_ARQOS;
reg[3:0] m_axi_gmem_x_train_0_ARREGION;
reg[0:0] m_axi_gmem_x_train_0_ARUSER;
reg m_axi_gmem_x_train_0_RREADY;
reg m_axi_gmem_y_train_0_ARVALID;
reg[63:0] m_axi_gmem_y_train_0_ARADDR;
reg[0:0] m_axi_gmem_y_train_0_ARID;
reg[31:0] m_axi_gmem_y_train_0_ARLEN;
reg[2:0] m_axi_gmem_y_train_0_ARSIZE;
reg[1:0] m_axi_gmem_y_train_0_ARBURST;
reg[1:0] m_axi_gmem_y_train_0_ARLOCK;
reg[3:0] m_axi_gmem_y_train_0_ARCACHE;
reg[2:0] m_axi_gmem_y_train_0_ARPROT;
reg[3:0] m_axi_gmem_y_train_0_ARQOS;
reg[3:0] m_axi_gmem_y_train_0_ARREGION;
reg[0:0] m_axi_gmem_y_train_0_ARUSER;
reg m_axi_gmem_y_train_0_RREADY;
reg[3:0] top_k_labels_0;
reg top_k_labels_0_ap_vld;
reg[3:0] top_k_labels_1;
reg top_k_labels_1_ap_vld;
reg[3:0] top_k_labels_2;
reg top_k_labels_2_ap_vld;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_x_train_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    gmem_y_train_blk_n_AR;
wire  signed [60:0] trunc_ln_fu_226_p4;
reg   [60:0] trunc_ln_reg_335;
wire  signed [61:0] trunc_ln41_1_fu_247_p4;
reg   [61:0] trunc_ln41_1_reg_345;
reg   [60:0] trunc_ln1_reg_355;
wire    ap_CS_fsm_state11;
reg   [1:0] i_reg_360;
wire    ap_CS_fsm_state15;
wire   [1:0] add_ln82_fu_306_p2;
reg   [1:0] add_ln82_reg_367;
reg   [3:0] distances_address0;
reg    distances_ce0;
reg    distances_we0;
reg   [63:0] distances_d0;
wire   [63:0] distances_q0;
reg    distances_ce1;
reg    distances_we1;
wire   [63:0] distances_q1;
reg   [3:0] labels_address0;
reg    labels_ce0;
reg    labels_we0;
reg   [3:0] labels_d0;
wire   [3:0] labels_q0;
reg    labels_ce1;
reg    labels_we1;
wire   [3:0] labels_q1;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_done;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_idle;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_ready;
wire   [3:0] grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0_ap_vld;
wire   [3:0] grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2_ap_vld;
wire   [3:0] grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1;
wire    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1_ap_vld;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_done;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_idle;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_ready;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_address0;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_ce0;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_we0;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_d0;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_address0;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_ce0;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_we0;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_d0;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWADDR;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWLEN;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWSIZE;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWBURST;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWLOCK;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWCACHE;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWPROT;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWQOS;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWREGION;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WVALID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WDATA;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WSTRB;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WLAST;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WID;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARADDR;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARLEN;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARSIZE;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARBURST;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARLOCK;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARCACHE;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARPROT;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARQOS;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARREGION;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_RREADY;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_BREADY;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWADDR;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWLEN;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWSIZE;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWBURST;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWLOCK;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWCACHE;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWPROT;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWQOS;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWREGION;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WDATA;
wire   [7:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WSTRB;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WLAST;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WID;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARADDR;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARLEN;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARSIZE;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARBURST;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARLOCK;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARCACHE;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARPROT;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARQOS;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARREGION;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_RREADY;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_BREADY;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWADDR;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWLEN;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWSIZE;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWBURST;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWLOCK;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWCACHE;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWPROT;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWQOS;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWREGION;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WDATA;
wire   [7:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WSTRB;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WLAST;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WID;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARVALID;
wire   [63:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARADDR;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARID;
wire   [31:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARLEN;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARSIZE;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARBURST;
wire   [1:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARLOCK;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARCACHE;
wire   [2:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARPROT;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARQOS;
wire   [3:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARREGION;
wire   [0:0] grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARUSER;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_RREADY;
wire    grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_BREADY;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_done;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_idle;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_ready;
wire   [3:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_address0;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_ce0;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_we0;
wire   [63:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_d0;
wire   [3:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_address1;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_ce1;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_we1;
wire   [63:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_d1;
wire   [3:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_address0;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_ce0;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_we0;
wire   [3:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_d0;
wire   [3:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_address1;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_ce1;
wire    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_we1;
wire   [3:0] grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_d1;
reg    grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start_reg;
reg   [3:0] top_k_labels_0_reg;
wire    ap_CS_fsm_state2;
reg   [3:0] top_k_labels_2_reg;
reg   [3:0] top_k_labels_1_reg;
reg    grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln82_fu_312_p1;
wire   [0:0] icmp_ln82_fu_300_p2;
wire  signed [63:0] sext_ln41_fu_236_p1;
wire  signed [63:0] sext_ln41_1_fu_257_p1;
reg    ap_block_state3_io;
reg   [1:0] i_5_fu_104;
wire    ap_CS_fsm_state16;
reg    labels_ce0_local;
wire   [11:0] shl_ln_fu_268_p3;
wire   [63:0] zext_ln41_fu_276_p1;
wire   [63:0] add_ln41_fu_280_p2;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start_reg = 1'b0;
#0 grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start_reg = 1'b0;
#0 grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start_reg = 1'b0;
#0 i_5_fu_104 = 2'd0;
end

knn_accelerator_knn_distance_and_sort_distances_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
distances_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(distances_address0),
    .ce0(distances_ce0),
    .we0(distances_we0),
    .d0(distances_d0),
    .q0(distances_q0),
    .address1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_address1),
    .ce1(distances_ce1),
    .we1(distances_we1),
    .d1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_d1),
    .q1(distances_q1)
);

knn_accelerator_knn_distance_and_sort_labels_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
labels_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(labels_address0),
    .ce0(labels_ce0),
    .we0(labels_we0),
    .d0(labels_d0),
    .q0(labels_q0),
    .address1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_address1),
    .ce1(labels_ce1),
    .we1(labels_we1),
    .d1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_d1),
    .q1(labels_q1)
);

knn_accelerator_knn_distance_and_sort_Outline_init_top_k grp_knn_distance_and_sort_Outline_init_top_k_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start),
    .ap_done(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_done),
    .ap_idle(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_idle),
    .ap_ready(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_ready),
    .top_k_labels_0(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0),
    .top_k_labels_0_ap_vld(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0_ap_vld),
    .top_k_labels_2(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2),
    .top_k_labels_2_ap_vld(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2_ap_vld),
    .top_k_labels_1(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1),
    .top_k_labels_1_ap_vld(grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1_ap_vld)
);

knn_accelerator_knn_distance_and_sort_Outline_train_loop grp_knn_distance_and_sort_Outline_train_loop_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start),
    .ap_done(grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_done),
    .ap_idle(grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_idle),
    .ap_ready(grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_ready),
    .distances_address0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_address0),
    .distances_ce0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_ce0),
    .distances_we0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_we0),
    .distances_d0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_d0),
    .labels_address0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_address0),
    .labels_ce0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_ce0),
    .labels_we0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_we0),
    .labels_d0(grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_d0),
    .m_axi_gmem_y_train_0_AWVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWVALID),
    .m_axi_gmem_y_train_0_AWREADY(1'b0),
    .m_axi_gmem_y_train_0_AWADDR(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWADDR),
    .m_axi_gmem_y_train_0_AWID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWID),
    .m_axi_gmem_y_train_0_AWLEN(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWLEN),
    .m_axi_gmem_y_train_0_AWSIZE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWSIZE),
    .m_axi_gmem_y_train_0_AWBURST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWBURST),
    .m_axi_gmem_y_train_0_AWLOCK(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWLOCK),
    .m_axi_gmem_y_train_0_AWCACHE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWCACHE),
    .m_axi_gmem_y_train_0_AWPROT(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWPROT),
    .m_axi_gmem_y_train_0_AWQOS(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWQOS),
    .m_axi_gmem_y_train_0_AWREGION(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWREGION),
    .m_axi_gmem_y_train_0_AWUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_AWUSER),
    .m_axi_gmem_y_train_0_WVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WVALID),
    .m_axi_gmem_y_train_0_WREADY(1'b0),
    .m_axi_gmem_y_train_0_WDATA(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WDATA),
    .m_axi_gmem_y_train_0_WSTRB(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WSTRB),
    .m_axi_gmem_y_train_0_WLAST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WLAST),
    .m_axi_gmem_y_train_0_WID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WID),
    .m_axi_gmem_y_train_0_WUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_WUSER),
    .m_axi_gmem_y_train_0_ARVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARVALID),
    .m_axi_gmem_y_train_0_ARREADY(m_axi_gmem_y_train_0_ARREADY),
    .m_axi_gmem_y_train_0_ARADDR(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARADDR),
    .m_axi_gmem_y_train_0_ARID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARID),
    .m_axi_gmem_y_train_0_ARLEN(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARLEN),
    .m_axi_gmem_y_train_0_ARSIZE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARSIZE),
    .m_axi_gmem_y_train_0_ARBURST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARBURST),
    .m_axi_gmem_y_train_0_ARLOCK(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARLOCK),
    .m_axi_gmem_y_train_0_ARCACHE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARCACHE),
    .m_axi_gmem_y_train_0_ARPROT(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARPROT),
    .m_axi_gmem_y_train_0_ARQOS(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARQOS),
    .m_axi_gmem_y_train_0_ARREGION(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARREGION),
    .m_axi_gmem_y_train_0_ARUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARUSER),
    .m_axi_gmem_y_train_0_RVALID(m_axi_gmem_y_train_0_RVALID),
    .m_axi_gmem_y_train_0_RREADY(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_RREADY),
    .m_axi_gmem_y_train_0_RDATA(m_axi_gmem_y_train_0_RDATA),
    .m_axi_gmem_y_train_0_RLAST(m_axi_gmem_y_train_0_RLAST),
    .m_axi_gmem_y_train_0_RID(m_axi_gmem_y_train_0_RID),
    .m_axi_gmem_y_train_0_RFIFONUM(m_axi_gmem_y_train_0_RFIFONUM),
    .m_axi_gmem_y_train_0_RUSER(m_axi_gmem_y_train_0_RUSER),
    .m_axi_gmem_y_train_0_RRESP(m_axi_gmem_y_train_0_RRESP),
    .m_axi_gmem_y_train_0_BVALID(1'b0),
    .m_axi_gmem_y_train_0_BREADY(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_BREADY),
    .m_axi_gmem_y_train_0_BRESP(2'd0),
    .m_axi_gmem_y_train_0_BID(1'd0),
    .m_axi_gmem_y_train_0_BUSER(1'd0),
    .sext_ln41_1(trunc_ln41_1_reg_345),
    .m_axi_gmem_x_test_0_AWVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWVALID),
    .m_axi_gmem_x_test_0_AWREADY(1'b0),
    .m_axi_gmem_x_test_0_AWADDR(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWADDR),
    .m_axi_gmem_x_test_0_AWID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWID),
    .m_axi_gmem_x_test_0_AWLEN(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWLEN),
    .m_axi_gmem_x_test_0_AWSIZE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWSIZE),
    .m_axi_gmem_x_test_0_AWBURST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWBURST),
    .m_axi_gmem_x_test_0_AWLOCK(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWLOCK),
    .m_axi_gmem_x_test_0_AWCACHE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWCACHE),
    .m_axi_gmem_x_test_0_AWPROT(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWPROT),
    .m_axi_gmem_x_test_0_AWQOS(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWQOS),
    .m_axi_gmem_x_test_0_AWREGION(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWREGION),
    .m_axi_gmem_x_test_0_AWUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_AWUSER),
    .m_axi_gmem_x_test_0_WVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WVALID),
    .m_axi_gmem_x_test_0_WREADY(1'b0),
    .m_axi_gmem_x_test_0_WDATA(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WDATA),
    .m_axi_gmem_x_test_0_WSTRB(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WSTRB),
    .m_axi_gmem_x_test_0_WLAST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WLAST),
    .m_axi_gmem_x_test_0_WID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WID),
    .m_axi_gmem_x_test_0_WUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_WUSER),
    .m_axi_gmem_x_test_0_ARVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARVALID),
    .m_axi_gmem_x_test_0_ARREADY(m_axi_gmem_x_test_0_ARREADY),
    .m_axi_gmem_x_test_0_ARADDR(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARADDR),
    .m_axi_gmem_x_test_0_ARID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARID),
    .m_axi_gmem_x_test_0_ARLEN(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARLEN),
    .m_axi_gmem_x_test_0_ARSIZE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARSIZE),
    .m_axi_gmem_x_test_0_ARBURST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARBURST),
    .m_axi_gmem_x_test_0_ARLOCK(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARLOCK),
    .m_axi_gmem_x_test_0_ARCACHE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARCACHE),
    .m_axi_gmem_x_test_0_ARPROT(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARPROT),
    .m_axi_gmem_x_test_0_ARQOS(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARQOS),
    .m_axi_gmem_x_test_0_ARREGION(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARREGION),
    .m_axi_gmem_x_test_0_ARUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARUSER),
    .m_axi_gmem_x_test_0_RVALID(m_axi_gmem_x_test_0_RVALID),
    .m_axi_gmem_x_test_0_RREADY(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_RREADY),
    .m_axi_gmem_x_test_0_RDATA(m_axi_gmem_x_test_0_RDATA),
    .m_axi_gmem_x_test_0_RLAST(m_axi_gmem_x_test_0_RLAST),
    .m_axi_gmem_x_test_0_RID(m_axi_gmem_x_test_0_RID),
    .m_axi_gmem_x_test_0_RFIFONUM(m_axi_gmem_x_test_0_RFIFONUM),
    .m_axi_gmem_x_test_0_RUSER(m_axi_gmem_x_test_0_RUSER),
    .m_axi_gmem_x_test_0_RRESP(m_axi_gmem_x_test_0_RRESP),
    .m_axi_gmem_x_test_0_BVALID(1'b0),
    .m_axi_gmem_x_test_0_BREADY(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_BREADY),
    .m_axi_gmem_x_test_0_BRESP(2'd0),
    .m_axi_gmem_x_test_0_BID(1'd0),
    .m_axi_gmem_x_test_0_BUSER(1'd0),
    .sext_ln52(trunc_ln1_reg_355),
    .m_axi_gmem_x_train_0_AWVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWVALID),
    .m_axi_gmem_x_train_0_AWREADY(1'b0),
    .m_axi_gmem_x_train_0_AWADDR(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWADDR),
    .m_axi_gmem_x_train_0_AWID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWID),
    .m_axi_gmem_x_train_0_AWLEN(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWLEN),
    .m_axi_gmem_x_train_0_AWSIZE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWSIZE),
    .m_axi_gmem_x_train_0_AWBURST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWBURST),
    .m_axi_gmem_x_train_0_AWLOCK(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWLOCK),
    .m_axi_gmem_x_train_0_AWCACHE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWCACHE),
    .m_axi_gmem_x_train_0_AWPROT(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWPROT),
    .m_axi_gmem_x_train_0_AWQOS(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWQOS),
    .m_axi_gmem_x_train_0_AWREGION(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWREGION),
    .m_axi_gmem_x_train_0_AWUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_AWUSER),
    .m_axi_gmem_x_train_0_WVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WVALID),
    .m_axi_gmem_x_train_0_WREADY(1'b0),
    .m_axi_gmem_x_train_0_WDATA(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WDATA),
    .m_axi_gmem_x_train_0_WSTRB(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WSTRB),
    .m_axi_gmem_x_train_0_WLAST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WLAST),
    .m_axi_gmem_x_train_0_WID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WID),
    .m_axi_gmem_x_train_0_WUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_WUSER),
    .m_axi_gmem_x_train_0_ARVALID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARVALID),
    .m_axi_gmem_x_train_0_ARREADY(m_axi_gmem_x_train_0_ARREADY),
    .m_axi_gmem_x_train_0_ARADDR(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARADDR),
    .m_axi_gmem_x_train_0_ARID(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARID),
    .m_axi_gmem_x_train_0_ARLEN(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARLEN),
    .m_axi_gmem_x_train_0_ARSIZE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARSIZE),
    .m_axi_gmem_x_train_0_ARBURST(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARBURST),
    .m_axi_gmem_x_train_0_ARLOCK(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARLOCK),
    .m_axi_gmem_x_train_0_ARCACHE(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARCACHE),
    .m_axi_gmem_x_train_0_ARPROT(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARPROT),
    .m_axi_gmem_x_train_0_ARQOS(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARQOS),
    .m_axi_gmem_x_train_0_ARREGION(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARREGION),
    .m_axi_gmem_x_train_0_ARUSER(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARUSER),
    .m_axi_gmem_x_train_0_RVALID(m_axi_gmem_x_train_0_RVALID),
    .m_axi_gmem_x_train_0_RREADY(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_RREADY),
    .m_axi_gmem_x_train_0_RDATA(m_axi_gmem_x_train_0_RDATA),
    .m_axi_gmem_x_train_0_RLAST(m_axi_gmem_x_train_0_RLAST),
    .m_axi_gmem_x_train_0_RID(m_axi_gmem_x_train_0_RID),
    .m_axi_gmem_x_train_0_RFIFONUM(m_axi_gmem_x_train_0_RFIFONUM),
    .m_axi_gmem_x_train_0_RUSER(m_axi_gmem_x_train_0_RUSER),
    .m_axi_gmem_x_train_0_RRESP(m_axi_gmem_x_train_0_RRESP),
    .m_axi_gmem_x_train_0_BVALID(1'b0),
    .m_axi_gmem_x_train_0_BREADY(grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_BREADY),
    .m_axi_gmem_x_train_0_BRESP(2'd0),
    .m_axi_gmem_x_train_0_BID(1'd0),
    .m_axi_gmem_x_train_0_BUSER(1'd0),
    .sext_ln41(trunc_ln_reg_335)
);

knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start),
    .ap_done(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_done),
    .ap_idle(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_idle),
    .ap_ready(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_ready),
    .distances_address0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_address0),
    .distances_ce0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_ce0),
    .distances_we0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_we0),
    .distances_d0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_d0),
    .distances_q0(distances_q0),
    .distances_address1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_address1),
    .distances_ce1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_ce1),
    .distances_we1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_we1),
    .distances_d1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_d1),
    .distances_q1(distances_q1),
    .labels_address0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_address0),
    .labels_ce0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_ce0),
    .labels_we0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_we0),
    .labels_d0(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_d0),
    .labels_q0(labels_q0),
    .labels_address1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_address1),
    .labels_ce1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_ce1),
    .labels_we1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_we1),
    .labels_d1(grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_d1),
    .labels_q1(labels_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_ready == 1'b1)) begin
            grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start_reg <= 1'b1;
        end else if ((grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_ready == 1'b1)) begin
            grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_ready == 1'b1)) begin
            grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_5_fu_104 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        i_5_fu_104 <= add_ln82_reg_367;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln82_reg_367 <= add_ln82_fu_306_p2;
        i_reg_360 <= i_5_fu_104;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        top_k_labels_0_reg <= grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        top_k_labels_1_reg <= grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        top_k_labels_2_reg <= grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        trunc_ln1_reg_355 <= {{add_ln41_fu_280_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln41_1_reg_345 <= {{y_train[63:2]}};
        trunc_ln_reg_335 <= {{X_train[63:3]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_io)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln82_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        distances_address0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distances_address0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_address0;
    end else begin
        distances_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        distances_ce0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distances_ce0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_ce0;
    end else begin
        distances_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        distances_ce1 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_ce1;
    end else begin
        distances_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        distances_d0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distances_d0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_d0;
    end else begin
        distances_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        distances_we0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        distances_we0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_distances_we0;
    end else begin
        distances_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        distances_we1 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_distances_we1;
    end else begin
        distances_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_x_train_blk_n_AR = m_axi_gmem_x_train_0_ARREADY;
    end else begin
        gmem_x_train_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_y_train_blk_n_AR = m_axi_gmem_y_train_0_ARREADY;
    end else begin
        gmem_y_train_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        labels_address0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        labels_address0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_address0;
    end else begin
        labels_address0 = zext_ln82_fu_312_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        labels_ce0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        labels_ce0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_ce0;
    end else begin
        labels_ce0 = labels_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        labels_ce0_local = 1'b1;
    end else begin
        labels_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        labels_ce1 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_ce1;
    end else begin
        labels_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        labels_d0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        labels_d0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_d0;
    end else begin
        labels_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        labels_we0 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        labels_we0 = grp_knn_distance_and_sort_Outline_train_loop_fu_200_labels_we0;
    end else begin
        labels_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        labels_we1 = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_labels_we1;
    end else begin
        labels_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_x_train_0_ARADDR = sext_ln41_fu_236_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARADDR = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARADDR;
    end else begin
        m_axi_gmem_x_train_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARBURST = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARBURST;
    end else begin
        m_axi_gmem_x_train_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARCACHE = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARCACHE;
    end else begin
        m_axi_gmem_x_train_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARID = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARID;
    end else begin
        m_axi_gmem_x_train_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_x_train_0_ARLEN = 64'd490;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARLEN = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARLEN;
    end else begin
        m_axi_gmem_x_train_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARLOCK = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARLOCK;
    end else begin
        m_axi_gmem_x_train_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARPROT = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARPROT;
    end else begin
        m_axi_gmem_x_train_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARQOS = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARQOS;
    end else begin
        m_axi_gmem_x_train_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARREGION = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARREGION;
    end else begin
        m_axi_gmem_x_train_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARSIZE = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARSIZE;
    end else begin
        m_axi_gmem_x_train_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARUSER = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARUSER;
    end else begin
        m_axi_gmem_x_train_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_x_train_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_ARVALID = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_ARVALID;
    end else begin
        m_axi_gmem_x_train_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_x_train_0_RREADY = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_train_0_RREADY;
    end else begin
        m_axi_gmem_x_train_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_y_train_0_ARADDR = sext_ln41_1_fu_257_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARADDR = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARADDR;
    end else begin
        m_axi_gmem_y_train_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARBURST = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARBURST;
    end else begin
        m_axi_gmem_y_train_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARCACHE = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARCACHE;
    end else begin
        m_axi_gmem_y_train_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARID = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARID;
    end else begin
        m_axi_gmem_y_train_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_y_train_0_ARLEN = 64'd10;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARLEN = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARLEN;
    end else begin
        m_axi_gmem_y_train_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARLOCK = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARLOCK;
    end else begin
        m_axi_gmem_y_train_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARPROT = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARPROT;
    end else begin
        m_axi_gmem_y_train_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARQOS = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARQOS;
    end else begin
        m_axi_gmem_y_train_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARREGION = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARREGION;
    end else begin
        m_axi_gmem_y_train_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARSIZE = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARSIZE;
    end else begin
        m_axi_gmem_y_train_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARUSER = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARUSER;
    end else begin
        m_axi_gmem_y_train_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_y_train_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_ARVALID = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_ARVALID;
    end else begin
        m_axi_gmem_y_train_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_y_train_0_RREADY = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_y_train_0_RREADY;
    end else begin
        m_axi_gmem_y_train_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((i_reg_360 == 2'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        top_k_labels_0 = labels_q0;
    end else if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        top_k_labels_0 = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0;
    end else begin
        top_k_labels_0 = top_k_labels_0_reg;
    end
end

always @ (*) begin
    if (((i_reg_360 == 2'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        top_k_labels_0_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_k_labels_0_ap_vld = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_0_ap_vld;
    end else begin
        top_k_labels_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((i_reg_360 == 2'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        top_k_labels_1 = labels_q0;
    end else if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        top_k_labels_1 = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1;
    end else begin
        top_k_labels_1 = top_k_labels_1_reg;
    end
end

always @ (*) begin
    if (((i_reg_360 == 2'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        top_k_labels_1_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_k_labels_1_ap_vld = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_1_ap_vld;
    end else begin
        top_k_labels_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~(i_reg_360 == 2'd0) & ~(i_reg_360 == 2'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        top_k_labels_2 = labels_q0;
    end else if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        top_k_labels_2 = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2;
    end else begin
        top_k_labels_2 = top_k_labels_2_reg;
    end
end

always @ (*) begin
    if ((~(i_reg_360 == 2'd0) & ~(i_reg_360 == 2'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        top_k_labels_2_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_k_labels_2_ap_vld = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_top_k_labels_2_ap_vld;
    end else begin
        top_k_labels_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln82_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln41_fu_280_p2 = (zext_ln41_fu_276_p1 + test_point);

assign add_ln82_fu_306_p2 = (i_5_fu_104 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem_y_train_0_ARREADY == 1'b0) | (m_axi_gmem_x_train_0_ARREADY == 1'b0));
end

assign grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start = grp_knn_distance_and_sort_Outline_init_top_k_fu_190_ap_start_reg;

assign grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start = grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215_ap_start_reg;

assign grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start = grp_knn_distance_and_sort_Outline_train_loop_fu_200_ap_start_reg;

assign icmp_ln82_fu_300_p2 = ((i_5_fu_104 == 2'd3) ? 1'b1 : 1'b0);

assign m_axi_gmem_x_test_0_ARADDR = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARADDR;

assign m_axi_gmem_x_test_0_ARBURST = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARBURST;

assign m_axi_gmem_x_test_0_ARCACHE = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARCACHE;

assign m_axi_gmem_x_test_0_ARID = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARID;

assign m_axi_gmem_x_test_0_ARLEN = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARLEN;

assign m_axi_gmem_x_test_0_ARLOCK = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARLOCK;

assign m_axi_gmem_x_test_0_ARPROT = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARPROT;

assign m_axi_gmem_x_test_0_ARQOS = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARQOS;

assign m_axi_gmem_x_test_0_ARREGION = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARREGION;

assign m_axi_gmem_x_test_0_ARSIZE = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARSIZE;

assign m_axi_gmem_x_test_0_ARUSER = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARUSER;

assign m_axi_gmem_x_test_0_ARVALID = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_ARVALID;

assign m_axi_gmem_x_test_0_AWADDR = 64'd0;

assign m_axi_gmem_x_test_0_AWBURST = 2'd0;

assign m_axi_gmem_x_test_0_AWCACHE = 4'd0;

assign m_axi_gmem_x_test_0_AWID = 1'd0;

assign m_axi_gmem_x_test_0_AWLEN = 32'd0;

assign m_axi_gmem_x_test_0_AWLOCK = 2'd0;

assign m_axi_gmem_x_test_0_AWPROT = 3'd0;

assign m_axi_gmem_x_test_0_AWQOS = 4'd0;

assign m_axi_gmem_x_test_0_AWREGION = 4'd0;

assign m_axi_gmem_x_test_0_AWSIZE = 3'd0;

assign m_axi_gmem_x_test_0_AWUSER = 1'd0;

assign m_axi_gmem_x_test_0_AWVALID = 1'b0;

assign m_axi_gmem_x_test_0_BREADY = 1'b0;

assign m_axi_gmem_x_test_0_RREADY = grp_knn_distance_and_sort_Outline_train_loop_fu_200_m_axi_gmem_x_test_0_RREADY;

assign m_axi_gmem_x_test_0_WDATA = 64'd0;

assign m_axi_gmem_x_test_0_WID = 1'd0;

assign m_axi_gmem_x_test_0_WLAST = 1'b0;

assign m_axi_gmem_x_test_0_WSTRB = 8'd0;

assign m_axi_gmem_x_test_0_WUSER = 1'd0;

assign m_axi_gmem_x_test_0_WVALID = 1'b0;

assign m_axi_gmem_x_train_0_AWADDR = 64'd0;

assign m_axi_gmem_x_train_0_AWBURST = 2'd0;

assign m_axi_gmem_x_train_0_AWCACHE = 4'd0;

assign m_axi_gmem_x_train_0_AWID = 1'd0;

assign m_axi_gmem_x_train_0_AWLEN = 32'd0;

assign m_axi_gmem_x_train_0_AWLOCK = 2'd0;

assign m_axi_gmem_x_train_0_AWPROT = 3'd0;

assign m_axi_gmem_x_train_0_AWQOS = 4'd0;

assign m_axi_gmem_x_train_0_AWREGION = 4'd0;

assign m_axi_gmem_x_train_0_AWSIZE = 3'd0;

assign m_axi_gmem_x_train_0_AWUSER = 1'd0;

assign m_axi_gmem_x_train_0_AWVALID = 1'b0;

assign m_axi_gmem_x_train_0_BREADY = 1'b0;

assign m_axi_gmem_x_train_0_WDATA = 64'd0;

assign m_axi_gmem_x_train_0_WID = 1'd0;

assign m_axi_gmem_x_train_0_WLAST = 1'b0;

assign m_axi_gmem_x_train_0_WSTRB = 8'd0;

assign m_axi_gmem_x_train_0_WUSER = 1'd0;

assign m_axi_gmem_x_train_0_WVALID = 1'b0;

assign m_axi_gmem_y_train_0_AWADDR = 64'd0;

assign m_axi_gmem_y_train_0_AWBURST = 2'd0;

assign m_axi_gmem_y_train_0_AWCACHE = 4'd0;

assign m_axi_gmem_y_train_0_AWID = 1'd0;

assign m_axi_gmem_y_train_0_AWLEN = 32'd0;

assign m_axi_gmem_y_train_0_AWLOCK = 2'd0;

assign m_axi_gmem_y_train_0_AWPROT = 3'd0;

assign m_axi_gmem_y_train_0_AWQOS = 4'd0;

assign m_axi_gmem_y_train_0_AWREGION = 4'd0;

assign m_axi_gmem_y_train_0_AWSIZE = 3'd0;

assign m_axi_gmem_y_train_0_AWUSER = 1'd0;

assign m_axi_gmem_y_train_0_AWVALID = 1'b0;

assign m_axi_gmem_y_train_0_BREADY = 1'b0;

assign m_axi_gmem_y_train_0_WDATA = 32'd0;

assign m_axi_gmem_y_train_0_WID = 1'd0;

assign m_axi_gmem_y_train_0_WLAST = 1'b0;

assign m_axi_gmem_y_train_0_WSTRB = 4'd0;

assign m_axi_gmem_y_train_0_WUSER = 1'd0;

assign m_axi_gmem_y_train_0_WVALID = 1'b0;

assign sext_ln41_1_fu_257_p1 = trunc_ln41_1_fu_247_p4;

assign sext_ln41_fu_236_p1 = trunc_ln_fu_226_p4;

assign shl_ln_fu_268_p3 = {{idx}, {3'd0}};

assign trunc_ln41_1_fu_247_p4 = {{y_train[63:2]}};

assign trunc_ln_fu_226_p4 = {{X_train[63:3]}};

assign zext_ln41_fu_276_p1 = shl_ln_fu_268_p3;

assign zext_ln82_fu_312_p1 = i_5_fu_104;

endmodule //knn_accelerator_knn_distance_and_sort
