// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        distances_address0,
        distances_ce0,
        distances_we0,
        distances_d0,
        distances_q0,
        distances_address1,
        distances_ce1,
        distances_we1,
        distances_d1,
        distances_q1,
        labels_address0,
        labels_ce0,
        labels_we0,
        labels_d0,
        labels_q0,
        labels_address1,
        labels_ce1,
        labels_we1,
        labels_d1,
        labels_q1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] distances_address0;
output   distances_ce0;
output   distances_we0;
output  [63:0] distances_d0;
input  [63:0] distances_q0;
output  [3:0] distances_address1;
output   distances_ce1;
output   distances_we1;
output  [63:0] distances_d1;
input  [63:0] distances_q1;
output  [3:0] labels_address0;
output   labels_ce0;
output   labels_we0;
output  [3:0] labels_d0;
input  [3:0] labels_q0;
output  [3:0] labels_address1;
output   labels_ce1;
output   labels_we1;
output  [3:0] labels_d1;
input  [3:0] labels_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] i_6_fu_142_p2;
reg   [3:0] i_6_reg_287;
wire    ap_CS_fsm_state2;
wire   [3:0] add_ln71_fu_157_p2;
reg   [3:0] add_ln71_reg_295;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln69_fu_163_p1;
reg   [63:0] zext_ln69_reg_300;
reg   [3:0] distances_addr_reg_305;
wire   [63:0] zext_ln71_fu_168_p1;
reg   [63:0] zext_ln71_reg_310;
reg   [3:0] distances_addr_1_reg_315;
reg   [63:0] temp_dist_reg_320;
wire    ap_CS_fsm_state4;
reg   [63:0] distances_load_1_reg_327;
wire   [0:0] and_ln71_1_fu_264_p2;
reg   [0:0] and_ln71_1_reg_334;
wire    ap_CS_fsm_state6;
reg   [3:0] labels_addr_reg_338;
reg   [3:0] labels_addr_1_reg_343;
reg   [3:0] j_reg_108;
wire   [0:0] icmp_ln67_fu_136_p2;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln69_fu_151_p2;
reg   [3:0] i_4_fu_48;
reg   [3:0] indvars_iv14_fu_52;
wire   [3:0] add_ln67_fu_173_p2;
reg    distances_ce1_local;
reg   [3:0] distances_address1_local;
reg    distances_ce0_local;
reg   [3:0] distances_address0_local;
reg    distances_we1_local;
reg    distances_we0_local;
reg    labels_ce1_local;
reg   [3:0] labels_address1_local;
reg    labels_ce0_local;
reg   [3:0] labels_address0_local;
reg    labels_we1_local;
reg    labels_we0_local;
wire    ap_CS_fsm_state5;
wire   [63:0] bitcast_ln71_fu_188_p1;
wire   [63:0] bitcast_ln71_1_fu_205_p1;
wire   [10:0] tmp_1_fu_191_p4;
wire   [51:0] trunc_ln71_fu_201_p1;
wire   [0:0] icmp_ln71_1_fu_228_p2;
wire   [0:0] icmp_ln71_fu_222_p2;
wire   [10:0] tmp_2_fu_208_p4;
wire   [51:0] trunc_ln71_1_fu_218_p1;
wire   [0:0] icmp_ln71_3_fu_246_p2;
wire   [0:0] icmp_ln71_2_fu_240_p2;
wire   [0:0] or_ln71_fu_234_p2;
wire   [0:0] or_ln71_1_fu_252_p2;
wire   [0:0] and_ln71_fu_258_p2;
wire   [0:0] grp_fu_119_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 i_4_fu_48 = 4'd0;
#0 indvars_iv14_fu_52 = 4'd0;
end

knn_accelerator_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_dist_reg_320),
    .din1(distances_load_1_reg_327),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_119_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_4_fu_48 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln69_fu_151_p2 == 1'd1))) begin
        i_4_fu_48 <= i_6_reg_287;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvars_iv14_fu_52 <= 4'd9;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln69_fu_151_p2 == 1'd1))) begin
        indvars_iv14_fu_52 <= add_ln67_fu_173_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        j_reg_108 <= add_ln71_reg_295;
    end else if (((icmp_ln67_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_108 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln71_reg_295 <= add_ln71_fu_157_p2;
        distances_addr_1_reg_315 <= zext_ln71_fu_168_p1;
        distances_addr_reg_305 <= zext_ln69_fu_163_p1;
        zext_ln69_reg_300[3 : 0] <= zext_ln69_fu_163_p1[3 : 0];
        zext_ln71_reg_310[3 : 0] <= zext_ln71_fu_168_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        and_ln71_1_reg_334 <= and_ln71_1_fu_264_p2;
        labels_addr_1_reg_343 <= zext_ln71_reg_310;
        labels_addr_reg_338 <= zext_ln69_reg_300;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        distances_load_1_reg_327 <= distances_q0;
        temp_dist_reg_320 <= distances_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_6_reg_287 <= i_6_fu_142_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln67_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        distances_address0_local = distances_addr_1_reg_315;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_address0_local = zext_ln71_fu_168_p1;
    end else begin
        distances_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        distances_address1_local = distances_addr_reg_305;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        distances_address1_local = zext_ln69_fu_163_p1;
    end else begin
        distances_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7))) begin
        distances_ce0_local = 1'b1;
    end else begin
        distances_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7))) begin
        distances_ce1_local = 1'b1;
    end else begin
        distances_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln71_1_reg_334))) begin
        distances_we0_local = 1'b1;
    end else begin
        distances_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln71_1_reg_334))) begin
        distances_we1_local = 1'b1;
    end else begin
        distances_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        labels_address0_local = labels_addr_1_reg_343;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        labels_address0_local = zext_ln71_reg_310;
    end else begin
        labels_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        labels_address1_local = labels_addr_reg_338;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        labels_address1_local = zext_ln69_reg_300;
    end else begin
        labels_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        labels_ce0_local = 1'b1;
    end else begin
        labels_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        labels_ce1_local = 1'b1;
    end else begin
        labels_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln71_1_reg_334))) begin
        labels_we0_local = 1'b1;
    end else begin
        labels_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln71_1_reg_334))) begin
        labels_we1_local = 1'b1;
    end else begin
        labels_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln67_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln69_fu_151_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_fu_173_p2 = ($signed(indvars_iv14_fu_52) + $signed(4'd15));

assign add_ln71_fu_157_p2 = (j_reg_108 + 4'd1);

assign and_ln71_1_fu_264_p2 = (grp_fu_119_p2 & and_ln71_fu_258_p2);

assign and_ln71_fu_258_p2 = (or_ln71_fu_234_p2 & or_ln71_1_fu_252_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign bitcast_ln71_1_fu_205_p1 = distances_load_1_reg_327;

assign bitcast_ln71_fu_188_p1 = temp_dist_reg_320;

assign distances_address0 = distances_address0_local;

assign distances_address1 = distances_address1_local;

assign distances_ce0 = distances_ce0_local;

assign distances_ce1 = distances_ce1_local;

assign distances_d0 = temp_dist_reg_320;

assign distances_d1 = distances_load_1_reg_327;

assign distances_we0 = distances_we0_local;

assign distances_we1 = distances_we1_local;

assign i_6_fu_142_p2 = (i_4_fu_48 + 4'd1);

assign icmp_ln67_fu_136_p2 = ((i_4_fu_48 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_151_p2 = ((j_reg_108 == indvars_iv14_fu_52) ? 1'b1 : 1'b0);

assign icmp_ln71_1_fu_228_p2 = ((trunc_ln71_fu_201_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln71_2_fu_240_p2 = ((tmp_2_fu_208_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln71_3_fu_246_p2 = ((trunc_ln71_1_fu_218_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_222_p2 = ((tmp_1_fu_191_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign labels_address0 = labels_address0_local;

assign labels_address1 = labels_address1_local;

assign labels_ce0 = labels_ce0_local;

assign labels_ce1 = labels_ce1_local;

assign labels_d0 = labels_q1;

assign labels_d1 = labels_q0;

assign labels_we0 = labels_we0_local;

assign labels_we1 = labels_we1_local;

assign or_ln71_1_fu_252_p2 = (icmp_ln71_3_fu_246_p2 | icmp_ln71_2_fu_240_p2);

assign or_ln71_fu_234_p2 = (icmp_ln71_fu_222_p2 | icmp_ln71_1_fu_228_p2);

assign tmp_1_fu_191_p4 = {{bitcast_ln71_fu_188_p1[62:52]}};

assign tmp_2_fu_208_p4 = {{bitcast_ln71_1_fu_205_p1[62:52]}};

assign trunc_ln71_1_fu_218_p1 = bitcast_ln71_1_fu_205_p1[51:0];

assign trunc_ln71_fu_201_p1 = bitcast_ln71_fu_188_p1[51:0];

assign zext_ln69_fu_163_p1 = j_reg_108;

assign zext_ln71_fu_168_p1 = add_ln71_fu_157_p2;

always @ (posedge ap_clk) begin
    zext_ln69_reg_300[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln71_reg_310[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i
