// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module knn_accelerator_knn_majority_vote (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        top_k_labels_read,
        top_k_labels_read_10,
        top_k_labels_read_11,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] top_k_labels_read;
input  [3:0] top_k_labels_read_10;
input  [3:0] top_k_labels_read_11;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
reg   [3:0] counts_address0;
reg    counts_ce0;
reg    counts_we0;
reg   [31:0] counts_d0;
wire   [31:0] counts_q0;
reg    counts_ce1;
wire   [31:0] counts_q1;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_idle;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_ready;
wire   [3:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0;
wire   [31:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_idle;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_ready;
wire   [3:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0;
wire   [31:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0;
wire   [3:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address1;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_idle;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_ready;
wire   [3:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0;
wire   [31:0] grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out;
wire    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out_ap_vld;
reg    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg = 1'b0;
#0 grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg = 1'b0;
#0 grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg = 1'b0;
end

knn_accelerator_knn_majority_vote_counts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
counts_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(counts_address0),
    .ce0(counts_ce0),
    .we0(counts_we0),
    .d0(counts_d0),
    .q0(counts_q0),
    .address1(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address1),
    .ce1(counts_ce1),
    .q1(counts_q1)
);

knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_95_1 grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start),
    .ap_done(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done),
    .ap_idle(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_idle),
    .ap_ready(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_ready),
    .counts_address0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0),
    .counts_ce0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0),
    .counts_we0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0),
    .counts_d0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0)
);

knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_106_2 grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start),
    .ap_done(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done),
    .ap_idle(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_idle),
    .ap_ready(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_ready),
    .top_k_labels_read(top_k_labels_read),
    .top_k_labels_read_3(top_k_labels_read_10),
    .top_k_labels_read_4(top_k_labels_read_11),
    .counts_address0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0),
    .counts_ce0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0),
    .counts_we0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0),
    .counts_d0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0),
    .counts_address1(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address1),
    .counts_ce1(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1),
    .counts_q1(counts_q1)
);

knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_119_3 grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start),
    .ap_done(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done),
    .ap_idle(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_idle),
    .ap_ready(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_ready),
    .counts_address0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0),
    .counts_ce0(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0),
    .counts_q0(counts_q0),
    .max_label_out(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out),
    .max_label_out_ap_vld(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_ready == 1'b1)) begin
            grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg <= 1'b1;
        end else if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_ready == 1'b1)) begin
            grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_ready == 1'b1)) begin
            grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        counts_address0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_address0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        counts_address0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0;
    end else begin
        counts_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        counts_ce0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_ce0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        counts_ce0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0;
    end else begin
        counts_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_ce1 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1;
    end else begin
        counts_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_d0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        counts_d0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0;
    end else begin
        counts_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        counts_we0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        counts_we0 = grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0;
    end else begin
        counts_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_return = grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out;

assign grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start = grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg;

assign grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start = grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg;

assign grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start = grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg;

endmodule //knn_accelerator_knn_majority_vote
