-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity knn_accelerator_knn_majority_vote is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    top_k_labels_read : IN STD_LOGIC_VECTOR (3 downto 0);
    top_k_labels_read_8 : IN STD_LOGIC_VECTOR (3 downto 0);
    top_k_labels_read_9 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of knn_accelerator_knn_majority_vote is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal counts_addr_1_reg_318 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_5_reg_343 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal counts_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln101_fu_146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln101_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln116_fu_193_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln113_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln127_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln127_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_54 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln101_fu_140_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_fu_62 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln113_fu_170_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal max_fu_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_1_fu_254_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal max_label_fu_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_label_1_fu_265_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_fu_74 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln127_fu_229_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal counts_we0_local : STD_LOGIC;
    signal counts_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal counts_ce0_local : STD_LOGIC;
    signal counts_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln116_fu_213_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_fu_176_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal idx_fu_176_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln129_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln129_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal idx_fu_176_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal idx_fu_176_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal idx_fu_176_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component knn_accelerator_sparsemux_7_2_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        def : IN STD_LOGIC_VECTOR (3 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component knn_accelerator_knn_majority_vote_counts_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    counts_U : component knn_accelerator_knn_majority_vote_counts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => counts_address0_local,
        ce0 => counts_ce0_local,
        we0 => counts_we0_local,
        d0 => counts_d0_local,
        q0 => counts_q0);

    sparsemux_7_2_4_1_1_U34 : component knn_accelerator_sparsemux_7_2_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 4,
        CASE1 => "01",
        din1_WIDTH => 4,
        CASE2 => "10",
        din2_WIDTH => 4,
        def_WIDTH => 4,
        sel_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => top_k_labels_read,
        din1 => top_k_labels_read_8,
        din2 => top_k_labels_read_9,
        def => idx_fu_176_p7,
        sel => i_1_fu_62,
        dout => idx_fu_176_p9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_1_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln101_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_1_fu_62 <= ap_const_lv2_0;
            elsif (((icmp_ln113_fu_164_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_1_fu_62 <= add_ln113_fu_170_p2;
            end if; 
        end if;
    end process;

    i_2_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_fu_164_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_2_fu_74 <= ap_const_lv4_0;
            elsif (((icmp_ln127_fu_223_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_2_fu_74 <= add_ln127_fu_229_p2;
            end if; 
        end if;
    end process;

    i_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_54 <= ap_const_lv4_0;
            elsif (((icmp_ln101_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_54 <= add_ln101_fu_140_p2;
            end if; 
        end if;
    end process;

    max_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_fu_164_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                max_fu_66 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                max_fu_66 <= max_1_fu_254_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                counts_addr_1_reg_318 <= zext_ln116_fu_193_p1(4 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_5_reg_343 <= i_2_fu_74;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                max_label_fu_70 <= max_label_1_fu_265_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state2, icmp_ln101_fu_134_p2, icmp_ln113_fu_164_p2, icmp_ln127_fu_223_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln101_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln113_fu_164_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln127_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln101_fu_140_p2 <= std_logic_vector(unsigned(i_fu_54) + unsigned(ap_const_lv4_1));
    add_ln113_fu_170_p2 <= std_logic_vector(unsigned(i_1_fu_62) + unsigned(ap_const_lv2_1));
    add_ln116_fu_213_p2 <= std_logic_vector(unsigned(counts_q0) + unsigned(ap_const_lv32_1));
    add_ln127_fu_229_p2 <= std_logic_vector(unsigned(i_2_fu_74) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5, icmp_ln127_fu_223_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((icmp_ln127_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln127_fu_223_p2)
    begin
        if (((icmp_ln127_fu_223_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= max_label_fu_70;

    counts_address0_local_assign_proc : process(counts_addr_1_reg_318, ap_CS_fsm_state3, ap_CS_fsm_state5, zext_ln101_fu_146_p1, ap_CS_fsm_state2, zext_ln116_fu_193_p1, zext_ln127_fu_235_p1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            counts_address0_local <= zext_ln127_fu_235_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_address0_local <= counts_addr_1_reg_318;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            counts_address0_local <= zext_ln116_fu_193_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            counts_address0_local <= zext_ln101_fu_146_p1(4 - 1 downto 0);
        else 
            counts_address0_local <= "XXXX";
        end if; 
    end process;


    counts_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            counts_ce0_local <= ap_const_logic_1;
        else 
            counts_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    counts_d0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, add_ln116_fu_213_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_d0_local <= add_ln116_fu_213_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            counts_d0_local <= ap_const_lv32_0;
        else 
            counts_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    counts_we0_local_assign_proc : process(ap_CS_fsm_state2, icmp_ln101_fu_134_p2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((icmp_ln101_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            counts_we0_local <= ap_const_logic_1;
        else 
            counts_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln101_fu_134_p2 <= "1" when (i_fu_54 = ap_const_lv4_A) else "0";
    icmp_ln113_fu_164_p2 <= "1" when (i_1_fu_62 = ap_const_lv2_3) else "0";
    icmp_ln127_fu_223_p2 <= "1" when (i_2_fu_74 = ap_const_lv4_A) else "0";
    icmp_ln129_fu_248_p2 <= "1" when (signed(counts_q0) > signed(max_fu_66)) else "0";
    idx_fu_176_p7 <= "XXXX";
    max_1_fu_254_p3 <= 
        counts_q0 when (icmp_ln129_fu_248_p2(0) = '1') else 
        max_fu_66;
    max_label_1_fu_265_p3 <= 
        zext_ln129_fu_262_p1 when (icmp_ln129_fu_248_p2(0) = '1') else 
        max_label_fu_70;
    zext_ln101_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_54),64));
    zext_ln116_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_fu_176_p9),64));
    zext_ln127_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_fu_74),64));
    zext_ln129_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_5_reg_343),32));
end behav;
