-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    distances_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    distances_ce0 : OUT STD_LOGIC;
    distances_we0 : OUT STD_LOGIC;
    distances_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    distances_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    distances_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    distances_ce1 : OUT STD_LOGIC;
    distances_we1 : OUT STD_LOGIC;
    distances_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    distances_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    labels_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_ce0 : OUT STD_LOGIC;
    labels_we0 : OUT STD_LOGIC;
    labels_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    labels_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_ce1 : OUT STD_LOGIC;
    labels_we1 : OUT STD_LOGIC;
    labels_d1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_q1 : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of knn_accelerator_knn_distance_and_sort_Outline_sort_loop_i is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_6_fu_142_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_6_reg_287 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln71_fu_157_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln71_reg_295 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln69_fu_163_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln69_reg_300 : STD_LOGIC_VECTOR (63 downto 0);
    signal distances_addr_reg_305 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln71_fu_168_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln71_reg_310 : STD_LOGIC_VECTOR (63 downto 0);
    signal distances_addr_1_reg_315 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_dist_reg_320 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal distances_load_1_reg_327 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln71_1_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln71_1_reg_334 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal labels_addr_reg_338 : STD_LOGIC_VECTOR (3 downto 0);
    signal labels_addr_1_reg_343 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_108 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln67_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln69_fu_151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_4_fu_48 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvars_iv14_fu_52 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln67_fu_173_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal distances_ce1_local : STD_LOGIC;
    signal distances_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal distances_ce0_local : STD_LOGIC;
    signal distances_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal distances_we1_local : STD_LOGIC;
    signal distances_we0_local : STD_LOGIC;
    signal labels_ce1_local : STD_LOGIC;
    signal labels_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal labels_ce0_local : STD_LOGIC;
    signal labels_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal labels_we1_local : STD_LOGIC;
    signal labels_we0_local : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal bitcast_ln71_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln71_1_fu_205_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_191_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln71_fu_201_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln71_1_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_208_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln71_1_fu_218_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln71_3_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_2_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln71_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln71_1_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln71_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component knn_accelerator_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    dcmp_64ns_64ns_1_2_no_dsp_1_U18 : component knn_accelerator_dcmp_64ns_64ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => temp_dist_reg_320,
        din1 => distances_load_1_reg_327,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_119_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_4_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_4_fu_48 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_fu_151_p2 = ap_const_lv1_1))) then 
                i_4_fu_48 <= i_6_reg_287;
            end if; 
        end if;
    end process;

    indvars_iv14_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvars_iv14_fu_52 <= ap_const_lv4_9;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_fu_151_p2 = ap_const_lv1_1))) then 
                indvars_iv14_fu_52 <= add_ln67_fu_173_p2;
            end if; 
        end if;
    end process;

    j_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                j_reg_108 <= add_ln71_reg_295;
            elsif (((icmp_ln67_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_108 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln71_reg_295 <= add_ln71_fu_157_p2;
                distances_addr_1_reg_315 <= zext_ln71_fu_168_p1(4 - 1 downto 0);
                distances_addr_reg_305 <= zext_ln69_fu_163_p1(4 - 1 downto 0);
                    zext_ln69_reg_300(3 downto 0) <= zext_ln69_fu_163_p1(3 downto 0);
                    zext_ln71_reg_310(3 downto 0) <= zext_ln71_fu_168_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                and_ln71_1_reg_334 <= and_ln71_1_fu_264_p2;
                labels_addr_1_reg_343 <= zext_ln71_reg_310(4 - 1 downto 0);
                labels_addr_reg_338 <= zext_ln69_reg_300(4 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                distances_load_1_reg_327 <= distances_q0;
                temp_dist_reg_320 <= distances_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_6_reg_287 <= i_6_fu_142_p2;
            end if;
        end if;
    end process;
    zext_ln69_reg_300(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    zext_ln71_reg_310(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln67_fu_136_p2, icmp_ln69_fu_151_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln67_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_fu_151_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln67_fu_173_p2 <= std_logic_vector(unsigned(indvars_iv14_fu_52) + unsigned(ap_const_lv4_F));
    add_ln71_fu_157_p2 <= std_logic_vector(unsigned(j_reg_108) + unsigned(ap_const_lv4_1));
    and_ln71_1_fu_264_p2 <= (grp_fu_119_p2 and and_ln71_fu_258_p2);
    and_ln71_fu_258_p2 <= (or_ln71_fu_234_p2 and or_ln71_1_fu_252_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln67_fu_136_p2)
    begin
        if ((((icmp_ln67_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln67_fu_136_p2)
    begin
        if (((icmp_ln67_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln71_1_fu_205_p1 <= distances_load_1_reg_327;
    bitcast_ln71_fu_188_p1 <= temp_dist_reg_320;
    distances_address0 <= distances_address0_local;

    distances_address0_local_assign_proc : process(ap_CS_fsm_state3, zext_ln71_fu_168_p1, distances_addr_1_reg_315, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            distances_address0_local <= distances_addr_1_reg_315;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            distances_address0_local <= zext_ln71_fu_168_p1(4 - 1 downto 0);
        else 
            distances_address0_local <= "XXXX";
        end if; 
    end process;

    distances_address1 <= distances_address1_local;

    distances_address1_local_assign_proc : process(ap_CS_fsm_state3, zext_ln69_fu_163_p1, distances_addr_reg_305, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            distances_address1_local <= distances_addr_reg_305;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            distances_address1_local <= zext_ln69_fu_163_p1(4 - 1 downto 0);
        else 
            distances_address1_local <= "XXXX";
        end if; 
    end process;

    distances_ce0 <= distances_ce0_local;

    distances_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            distances_ce0_local <= ap_const_logic_1;
        else 
            distances_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    distances_ce1 <= distances_ce1_local;

    distances_ce1_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            distances_ce1_local <= ap_const_logic_1;
        else 
            distances_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    distances_d0 <= temp_dist_reg_320;
    distances_d1 <= distances_load_1_reg_327;
    distances_we0 <= distances_we0_local;

    distances_we0_local_assign_proc : process(and_ln71_1_reg_334, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = and_ln71_1_reg_334))) then 
            distances_we0_local <= ap_const_logic_1;
        else 
            distances_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    distances_we1 <= distances_we1_local;

    distances_we1_local_assign_proc : process(and_ln71_1_reg_334, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = and_ln71_1_reg_334))) then 
            distances_we1_local <= ap_const_logic_1;
        else 
            distances_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    i_6_fu_142_p2 <= std_logic_vector(unsigned(i_4_fu_48) + unsigned(ap_const_lv4_1));
    icmp_ln67_fu_136_p2 <= "1" when (i_4_fu_48 = ap_const_lv4_9) else "0";
    icmp_ln69_fu_151_p2 <= "1" when (j_reg_108 = indvars_iv14_fu_52) else "0";
    icmp_ln71_1_fu_228_p2 <= "1" when (trunc_ln71_fu_201_p1 = ap_const_lv52_0) else "0";
    icmp_ln71_2_fu_240_p2 <= "0" when (tmp_2_fu_208_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln71_3_fu_246_p2 <= "1" when (trunc_ln71_1_fu_218_p1 = ap_const_lv52_0) else "0";
    icmp_ln71_fu_222_p2 <= "0" when (tmp_1_fu_191_p4 = ap_const_lv11_7FF) else "1";
    labels_address0 <= labels_address0_local;

    labels_address0_local_assign_proc : process(zext_ln71_reg_310, ap_CS_fsm_state6, labels_addr_1_reg_343, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            labels_address0_local <= labels_addr_1_reg_343;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            labels_address0_local <= zext_ln71_reg_310(4 - 1 downto 0);
        else 
            labels_address0_local <= "XXXX";
        end if; 
    end process;

    labels_address1 <= labels_address1_local;

    labels_address1_local_assign_proc : process(zext_ln69_reg_300, ap_CS_fsm_state6, labels_addr_reg_338, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            labels_address1_local <= labels_addr_reg_338;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            labels_address1_local <= zext_ln69_reg_300(4 - 1 downto 0);
        else 
            labels_address1_local <= "XXXX";
        end if; 
    end process;

    labels_ce0 <= labels_ce0_local;

    labels_ce0_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            labels_ce0_local <= ap_const_logic_1;
        else 
            labels_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    labels_ce1 <= labels_ce1_local;

    labels_ce1_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            labels_ce1_local <= ap_const_logic_1;
        else 
            labels_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    labels_d0 <= labels_q1;
    labels_d1 <= labels_q0;
    labels_we0 <= labels_we0_local;

    labels_we0_local_assign_proc : process(and_ln71_1_reg_334, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = and_ln71_1_reg_334))) then 
            labels_we0_local <= ap_const_logic_1;
        else 
            labels_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    labels_we1 <= labels_we1_local;

    labels_we1_local_assign_proc : process(and_ln71_1_reg_334, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = and_ln71_1_reg_334))) then 
            labels_we1_local <= ap_const_logic_1;
        else 
            labels_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln71_1_fu_252_p2 <= (icmp_ln71_3_fu_246_p2 or icmp_ln71_2_fu_240_p2);
    or_ln71_fu_234_p2 <= (icmp_ln71_fu_222_p2 or icmp_ln71_1_fu_228_p2);
    tmp_1_fu_191_p4 <= bitcast_ln71_fu_188_p1(62 downto 52);
    tmp_2_fu_208_p4 <= bitcast_ln71_1_fu_205_p1(62 downto 52);
    trunc_ln71_1_fu_218_p1 <= bitcast_ln71_1_fu_205_p1(52 - 1 downto 0);
    trunc_ln71_fu_201_p1 <= bitcast_ln71_fu_188_p1(52 - 1 downto 0);
    zext_ln69_fu_163_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_108),64));
    zext_ln71_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln71_fu_157_p2),64));
end behav;
