-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity knn_accelerator_knn_majority_vote is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    top_k_labels_read : IN STD_LOGIC_VECTOR (3 downto 0);
    top_k_labels_read_10 : IN STD_LOGIC_VECTOR (3 downto 0);
    top_k_labels_read_11 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of knn_accelerator_knn_majority_vote is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal counts_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal counts_ce0 : STD_LOGIC;
    signal counts_we0 : STD_LOGIC;
    signal counts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal counts_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal counts_ce1 : STD_LOGIC;
    signal counts_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_idle : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_ready : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0 : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0 : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_idle : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_ready : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0 : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0 : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1 : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_idle : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_ready : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0 : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out_ap_vld : STD_LOGIC;
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_95_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        counts_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        counts_ce0 : OUT STD_LOGIC;
        counts_we0 : OUT STD_LOGIC;
        counts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_106_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        top_k_labels_read : IN STD_LOGIC_VECTOR (3 downto 0);
        top_k_labels_read_3 : IN STD_LOGIC_VECTOR (3 downto 0);
        top_k_labels_read_4 : IN STD_LOGIC_VECTOR (3 downto 0);
        counts_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        counts_ce0 : OUT STD_LOGIC;
        counts_we0 : OUT STD_LOGIC;
        counts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        counts_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        counts_ce1 : OUT STD_LOGIC;
        counts_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_119_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        counts_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        counts_ce0 : OUT STD_LOGIC;
        counts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        max_label_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        max_label_out_ap_vld : OUT STD_LOGIC );
    end component;


    component knn_accelerator_knn_majority_vote_counts_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    counts_U : component knn_accelerator_knn_majority_vote_counts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => counts_address0,
        ce0 => counts_ce0,
        we0 => counts_we0,
        d0 => counts_d0,
        q0 => counts_q0,
        address1 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address1,
        ce1 => counts_ce1,
        q1 => counts_q1);

    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42 : component knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_95_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start,
        ap_done => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done,
        ap_idle => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_idle,
        ap_ready => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_ready,
        counts_address0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0,
        counts_ce0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0,
        counts_we0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0,
        counts_d0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0);

    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48 : component knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_106_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start,
        ap_done => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done,
        ap_idle => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_idle,
        ap_ready => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_ready,
        top_k_labels_read => top_k_labels_read,
        top_k_labels_read_3 => top_k_labels_read_10,
        top_k_labels_read_4 => top_k_labels_read_11,
        counts_address0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0,
        counts_ce0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0,
        counts_we0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0,
        counts_d0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0,
        counts_address1 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address1,
        counts_ce1 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1,
        counts_q1 => counts_q1);

    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59 : component knn_accelerator_knn_majority_vote_Pipeline_VITIS_LOOP_119_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start,
        ap_done => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done,
        ap_idle => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_idle,
        ap_ready => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_ready,
        counts_address0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0,
        counts_ce0 => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0,
        counts_q0 => counts_q0,
        max_label_out => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out,
        max_label_out_ap_vld => grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_ready = ap_const_logic_1)) then 
                    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_ready = ap_const_logic_1)) then 
                    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done, grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done, grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done)
    begin
        if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done)
    begin
        if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done)
    begin
        if ((grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_max_label_out;

    counts_address0_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0, grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0, grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            counts_address0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_address0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            counts_address0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_address0;
        else 
            counts_address0 <= "XXXX";
        end if; 
    end process;


    counts_ce0_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0, grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0, grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            counts_ce0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_counts_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_ce0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            counts_ce0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_ce0;
        else 
            counts_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    counts_ce1_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_ce1 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_ce1;
        else 
            counts_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    counts_d0_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0, grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_d0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            counts_d0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_d0;
        else 
            counts_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    counts_we0_assign_proc : process(grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0, grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            counts_we0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_counts_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            counts_we0 <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_counts_we0;
        else 
            counts_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48_ap_start_reg;
    grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59_ap_start_reg;
    grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start <= grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42_ap_start_reg;
end behav;
