-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    indvars_iv14 : IN STD_LOGIC_VECTOR (10 downto 0);
    distances_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    distances_ce0 : OUT STD_LOGIC;
    distances_we0 : OUT STD_LOGIC;
    distances_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    distances_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    distances_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    distances_ce1 : OUT STD_LOGIC;
    distances_we1 : OUT STD_LOGIC;
    distances_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    distances_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    labels_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    labels_ce0 : OUT STD_LOGIC;
    labels_we0 : OUT STD_LOGIC;
    labels_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    labels_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    labels_ce1 : OUT STD_LOGIC;
    labels_we1 : OUT STD_LOGIC;
    labels_d1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    labels_q1 : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of knn_accelerator_knn_distance_and_sort_Pipeline_sort_loop_j is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln65_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln65_reg_235 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln66_fu_126_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln66_reg_239 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln65_fu_132_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_reg_244 : STD_LOGIC_VECTOR (63 downto 0);
    signal distances_addr_reg_249 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln66_fu_137_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln66_reg_254 : STD_LOGIC_VECTOR (63 downto 0);
    signal distances_addr_1_reg_259 : STD_LOGIC_VECTOR (10 downto 0);
    signal temp_dist_reg_264 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal distances_load_1_reg_271 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln66_1_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln66_1_reg_278 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal labels_addr_reg_282 : STD_LOGIC_VECTOR (10 downto 0);
    signal labels_addr_1_reg_287 : STD_LOGIC_VECTOR (10 downto 0);
    signal j_fu_46 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal distances_ce1_local : STD_LOGIC;
    signal distances_address1_local : STD_LOGIC_VECTOR (10 downto 0);
    signal distances_ce0_local : STD_LOGIC;
    signal distances_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal distances_we1_local : STD_LOGIC;
    signal distances_we0_local : STD_LOGIC;
    signal labels_ce1_local : STD_LOGIC;
    signal labels_address1_local : STD_LOGIC_VECTOR (10 downto 0);
    signal labels_ce0_local : STD_LOGIC;
    signal labels_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal labels_we1_local : STD_LOGIC;
    signal labels_we0_local : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bitcast_ln66_fu_142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln66_1_fu_159_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_145_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln66_fu_155_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln66_1_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_162_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln66_1_fu_172_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln66_3_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln66_1_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln66_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component knn_accelerator_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component knn_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dcmp_64ns_64ns_1_2_no_dsp_1_U19 : component knn_accelerator_dcmp_64ns_64ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => temp_dist_reg_264,
        din1 => distances_load_1_reg_271,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_108_p2);

    flow_control_loop_pipe_sequential_init_U : component knn_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                j_fu_46 <= ap_const_lv11_0;
            elsif (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_fu_46 <= add_ln66_reg_239;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln66_reg_239 <= add_ln66_fu_126_p2;
                distances_addr_1_reg_259 <= zext_ln66_fu_137_p1(11 - 1 downto 0);
                distances_addr_reg_249 <= zext_ln65_fu_132_p1(11 - 1 downto 0);
                icmp_ln65_reg_235 <= icmp_ln65_fu_120_p2;
                    zext_ln65_reg_244(10 downto 0) <= zext_ln65_fu_132_p1(10 downto 0);
                    zext_ln66_reg_254(10 downto 0) <= zext_ln66_fu_137_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                and_ln66_1_reg_278 <= and_ln66_1_fu_218_p2;
                labels_addr_1_reg_287 <= zext_ln66_reg_254(11 - 1 downto 0);
                labels_addr_reg_282 <= zext_ln65_reg_244(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                distances_load_1_reg_271 <= distances_q0;
                temp_dist_reg_264 <= distances_q1;
            end if;
        end if;
    end process;
    zext_ln65_reg_244(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln66_reg_254(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln65_fu_120_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln65_fu_120_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln66_fu_126_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv11_1));
    and_ln66_1_fu_218_p2 <= (grp_fu_108_p2 and and_ln66_fu_212_p2);
    and_ln66_fu_212_p2 <= (or_ln66_fu_188_p2 and or_ln66_1_fu_206_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln65_fu_120_p2)
    begin
        if (((icmp_ln65_fu_120_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_state1, j_fu_46, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_46;
        end if; 
    end process;

    bitcast_ln66_1_fu_159_p1 <= distances_load_1_reg_271;
    bitcast_ln66_fu_142_p1 <= temp_dist_reg_264;
    distances_address0 <= distances_address0_local;

    distances_address0_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln65_fu_120_p2, ap_CS_fsm_state5, icmp_ln65_reg_235, zext_ln66_fu_137_p1, distances_addr_1_reg_259, and_ln66_1_reg_278)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            distances_address0_local <= distances_addr_1_reg_259;
        elsif (((icmp_ln65_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            distances_address0_local <= zext_ln66_fu_137_p1(11 - 1 downto 0);
        else 
            distances_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    distances_address1 <= distances_address1_local;

    distances_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln65_fu_120_p2, ap_CS_fsm_state5, icmp_ln65_reg_235, zext_ln65_fu_132_p1, distances_addr_reg_249, and_ln66_1_reg_278)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            distances_address1_local <= distances_addr_reg_249;
        elsif (((icmp_ln65_fu_120_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            distances_address1_local <= zext_ln65_fu_132_p1(11 - 1 downto 0);
        else 
            distances_address1_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    distances_ce0 <= distances_ce0_local;

    distances_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln65_fu_120_p2, ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_reg_278)
    begin
        if ((((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln65_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            distances_ce0_local <= ap_const_logic_1;
        else 
            distances_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    distances_ce1 <= distances_ce1_local;

    distances_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln65_fu_120_p2, ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_reg_278)
    begin
        if ((((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln65_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            distances_ce1_local <= ap_const_logic_1;
        else 
            distances_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    distances_d0 <= temp_dist_reg_264;
    distances_d1 <= distances_load_1_reg_271;
    distances_we0 <= distances_we0_local;

    distances_we0_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_reg_278)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            distances_we0_local <= ap_const_logic_1;
        else 
            distances_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    distances_we1 <= distances_we1_local;

    distances_we1_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_reg_278)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            distances_we1_local <= ap_const_logic_1;
        else 
            distances_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln65_fu_120_p2 <= "1" when (ap_sig_allocacmp_j_1 = indvars_iv14) else "0";
    icmp_ln66_1_fu_182_p2 <= "1" when (trunc_ln66_fu_155_p1 = ap_const_lv52_0) else "0";
    icmp_ln66_2_fu_194_p2 <= "0" when (tmp_2_fu_162_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln66_3_fu_200_p2 <= "1" when (trunc_ln66_1_fu_172_p1 = ap_const_lv52_0) else "0";
    icmp_ln66_fu_176_p2 <= "0" when (tmp_1_fu_145_p4 = ap_const_lv11_7FF) else "1";
    labels_address0 <= labels_address0_local;

    labels_address0_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, zext_ln66_reg_254, and_ln66_1_fu_218_p2, and_ln66_1_reg_278, ap_CS_fsm_state4, labels_addr_1_reg_287)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            labels_address0_local <= labels_addr_1_reg_287;
        elsif (((ap_const_lv1_1 = and_ln66_1_fu_218_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            labels_address0_local <= zext_ln66_reg_254(11 - 1 downto 0);
        else 
            labels_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    labels_address1 <= labels_address1_local;

    labels_address1_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, zext_ln65_reg_244, and_ln66_1_fu_218_p2, and_ln66_1_reg_278, ap_CS_fsm_state4, labels_addr_reg_282)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            labels_address1_local <= labels_addr_reg_282;
        elsif (((ap_const_lv1_1 = and_ln66_1_fu_218_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            labels_address1_local <= zext_ln65_reg_244(11 - 1 downto 0);
        else 
            labels_address1_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    labels_ce0 <= labels_ce0_local;

    labels_ce0_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_fu_218_p2, and_ln66_1_reg_278, ap_CS_fsm_state4)
    begin
        if ((((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_lv1_1 = and_ln66_1_fu_218_p2) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            labels_ce0_local <= ap_const_logic_1;
        else 
            labels_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    labels_ce1 <= labels_ce1_local;

    labels_ce1_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_fu_218_p2, and_ln66_1_reg_278, ap_CS_fsm_state4)
    begin
        if ((((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_lv1_1 = and_ln66_1_fu_218_p2) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            labels_ce1_local <= ap_const_logic_1;
        else 
            labels_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    labels_d0 <= labels_q1;
    labels_d1 <= labels_q0;
    labels_we0 <= labels_we0_local;

    labels_we0_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_reg_278)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            labels_we0_local <= ap_const_logic_1;
        else 
            labels_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    labels_we1 <= labels_we1_local;

    labels_we1_local_assign_proc : process(ap_CS_fsm_state5, icmp_ln65_reg_235, and_ln66_1_reg_278)
    begin
        if (((icmp_ln65_reg_235 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln66_1_reg_278) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            labels_we1_local <= ap_const_logic_1;
        else 
            labels_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln66_1_fu_206_p2 <= (icmp_ln66_3_fu_200_p2 or icmp_ln66_2_fu_194_p2);
    or_ln66_fu_188_p2 <= (icmp_ln66_fu_176_p2 or icmp_ln66_1_fu_182_p2);
    tmp_1_fu_145_p4 <= bitcast_ln66_fu_142_p1(62 downto 52);
    tmp_2_fu_162_p4 <= bitcast_ln66_1_fu_159_p1(62 downto 52);
    trunc_ln66_1_fu_172_p1 <= bitcast_ln66_1_fu_159_p1(52 - 1 downto 0);
    trunc_ln66_fu_155_p1 <= bitcast_ln66_fu_142_p1(52 - 1 downto 0);
    zext_ln65_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_1),64));
    zext_ln66_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln66_fu_126_p2),64));
end behav;
