

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "11", "14", "15", "16", "17", "18", "19"],
		"CDFG" : "knn_accelerator",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "120747", "EstimateLatencyMax" : "124347",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_x_test", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_knn_distance_and_sort_fu_178", "Port" : "gmem_x_test", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "gmem_x_train", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_knn_distance_and_sort_fu_178", "Port" : "gmem_x_train", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "gmem_y_train", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_knn_distance_and_sort_fu_178", "Port" : "gmem_y_train", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "gmem_y_test", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_y_test_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_y_test_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_y_test_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "X_test", "Type" : "None", "Direction" : "I"},
			{"Name" : "X_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_test", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "test_data", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "13", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state8"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state9"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178", "Parent" : "0", "Child" : ["2", "3", "4", "5", "9"],
		"CDFG" : "knn_distance_and_sort",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "12029", "EstimateLatencyMax" : "12389",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_x_test", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_knn_distance_and_sort_Outline_train_loop_fu_200", "Port" : "gmem_x_test", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "test_point", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_x_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_x_train_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_knn_distance_and_sort_Outline_train_loop_fu_200", "Port" : "gmem_x_train", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "X_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_y_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_y_train_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_knn_distance_and_sort_Outline_train_loop_fu_200", "Port" : "gmem_y_train", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "y_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_0", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_knn_distance_and_sort_Outline_init_top_k_fu_190", "Port" : "top_k_labels_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "top_k_labels_1", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_knn_distance_and_sort_Outline_init_top_k_fu_190", "Port" : "top_k_labels_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "top_k_labels_2", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_knn_distance_and_sort_Outline_init_top_k_fu_190", "Port" : "top_k_labels_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "idx", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "copy_top_k", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "16", "FirstState" : "ap_ST_fsm_state15", "LastState" : ["ap_ST_fsm_state16"], "QuitState" : ["ap_ST_fsm_state15"], "PreState" : ["ap_ST_fsm_state14"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.distances_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.labels_U", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_init_top_k_fu_190", "Parent" : "1",
		"CDFG" : "knn_distance_and_sort_Outline_init_top_k",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "top_k_labels_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_k_labels_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_k_labels_1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "init_top_k", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state2"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "1", "OneStateBlock": "ap_ST_fsm_state2_blk"}}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_train_loop_fu_200", "Parent" : "1", "Child" : ["6", "7", "8"],
		"CDFG" : "knn_distance_and_sort_Outline_train_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11941", "EstimateLatencyMax" : "11941",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "distances", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "labels", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "gmem_y_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_y_train_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln41_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_x_test", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_x_test_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_x_test_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln52", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_x_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_x_train_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln41", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "feature_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state11", "LastState" : ["ap_ST_fsm_state33"], "QuitState" : ["ap_ST_fsm_state11"], "PreState" : ["ap_ST_fsm_state10"], "PostState" : ["ap_ST_fsm_state34"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "train_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state90"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_train_loop_fu_200.dadddsub_64ns_64ns_64_7_full_dsp_1_U4", "Parent" : "5"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_train_loop_fu_200.dmul_64ns_64ns_64_7_max_dsp_1_U5", "Parent" : "5"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_train_loop_fu_200.dsqrt_64ns_64ns_64_57_no_dsp_1_U6", "Parent" : "5"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215", "Parent" : "1", "Child" : ["10"],
		"CDFG" : "knn_distance_and_sort_Outline_sort_loop_i",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "64", "EstimateLatencyMax" : "424",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "distances", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "labels", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "sort_loop_j", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "7", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state7"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "sort_loop_i", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "7", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_178.grp_knn_distance_and_sort_Outline_sort_loop_i_fu_215.dcmp_64ns_64ns_1_2_no_dsp_1_U18", "Parent" : "9"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_195", "Parent" : "0", "Child" : ["12", "13"],
		"CDFG" : "knn_majority_vote",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "39", "EstimateLatencyMax" : "39",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "top_k_labels_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_read_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_read_9", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "count_init_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "6", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state2"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state3"], "OneDepthLoop" : "1", "OneStateBlock": "ap_ST_fsm_state2_blk"}},
			{"Name" : "set_counts_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "6", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state5"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "max_count_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "6", "FirstState" : "ap_ST_fsm_state5", "LastState" : ["ap_ST_fsm_state6"], "QuitState" : ["ap_ST_fsm_state5"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_195.counts_U", "Parent" : "11"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_195.sparsemux_7_2_4_1_1_U34", "Parent" : "11"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_r_s_axi_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_x_test_m_axi_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_x_train_m_axi_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_y_test_m_axi_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_y_train_m_axi_U", "Parent" : "0"}]}
