

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "18", "27", "28", "29", "30", "31", "32"],
		"CDFG" : "knn_accelerator",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "87443007", "EstimateLatencyMax" : "11314953007",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_x_test", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_knn_distance_and_sort_fu_176", "Port" : "gmem_x_test", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "gmem_x_train", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_knn_distance_and_sort_fu_176", "Port" : "gmem_x_train", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "gmem_y_train", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_knn_distance_and_sort_fu_176", "Port" : "gmem_y_train", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "gmem_y_test", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_y_test_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_y_test_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_y_test_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "X_test", "Type" : "None", "Direction" : "I"},
			{"Name" : "X_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "y_test", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "test_data", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "12", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state7"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state8"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176", "Parent" : "0", "Child" : ["2", "3", "4", "6", "12", "16"],
		"CDFG" : "knn_distance_and_sort",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "87400", "EstimateLatencyMax" : "11314910",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_x_test", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_train_loop_fu_138", "Port" : "gmem_x_test", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "test_point", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_x_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_x_train_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_train_loop_fu_138", "Port" : "gmem_x_train", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "X_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_y_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_y_train_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_train_loop_fu_138", "Port" : "gmem_y_train", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "y_train", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_0", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_init_top_k_fu_128", "Port" : "top_k_labels_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "16", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_copy_top_k_fu_159", "Port" : "top_k_labels_0", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "top_k_labels_1", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_init_top_k_fu_128", "Port" : "top_k_labels_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "16", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_copy_top_k_fu_159", "Port" : "top_k_labels_1", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "top_k_labels_2", "Type" : "Vld", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_init_top_k_fu_128", "Port" : "top_k_labels_2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "16", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_copy_top_k_fu_159", "Port" : "top_k_labels_2", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "idx", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.distances_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.labels_U", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_init_top_k_fu_128", "Parent" : "1", "Child" : ["5"],
		"CDFG" : "knn_distance_and_sort_Pipeline_init_top_k",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "top_k_labels_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_k_labels_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_k_labels_1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "init_top_k", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "5", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_init_top_k_fu_128.flow_control_loop_pipe_sequential_init_U", "Parent" : "4"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_train_loop_fu_138", "Parent" : "1", "Child" : ["7", "8", "9", "10", "11"],
		"CDFG" : "knn_distance_and_sort_Pipeline_train_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "73883", "EstimateLatencyMax" : "73883",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_x_test", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_x_test_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_x_test_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "p_cast_cast", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_x_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_x_train_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln40", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_y_train", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_y_train_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln40_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "distances", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "labels", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "train_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "49", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage38", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage38_subdone", "QuitState" : "ap_ST_fsm_pp0_stage38", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage38_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_train_loop_fu_138.dadddsub_64ns_64ns_64_7_full_dsp_1_U4", "Parent" : "6"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_train_loop_fu_138.dadddsub_64ns_64ns_64_7_full_dsp_1_U5", "Parent" : "6"},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_train_loop_fu_138.dmul_64ns_64ns_64_7_max_dsp_1_U6", "Parent" : "6"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_train_loop_fu_138.dsqrt_64ns_64ns_64_57_no_dsp_1_U7", "Parent" : "6"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_train_loop_fu_138.flow_control_loop_pipe_sequential_init_U", "Parent" : "6"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Outline_sort_loop_i_fu_153", "Parent" : "1", "Child" : ["13"],
		"CDFG" : "knn_distance_and_sort_Outline_sort_loop_i",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "13492", "EstimateLatencyMax" : "11241002",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "distances", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32", "Port" : "distances", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "labels", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32", "Port" : "labels", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}],
		"Loop" : [
			{"Name" : "sort_loop_i", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Outline_sort_loop_i_fu_153.grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32", "Parent" : "12", "Child" : ["14", "15"],
		"CDFG" : "knn_distance_and_sort_Pipeline_sort_loop_j",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "7", "EstimateLatencyMax" : "7497",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "indvars_iv14", "Type" : "None", "Direction" : "I"},
			{"Name" : "distances", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "labels", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "sort_loop_j", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state5", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state5_blk", "QuitState" : "ap_ST_fsm_state5", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state5_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "14", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Outline_sort_loop_i_fu_153.grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32.dcmp_64ns_64ns_1_2_no_dsp_1_U19", "Parent" : "13"},
	{"ID" : "15", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Outline_sort_loop_i_fu_153.grp_knn_distance_and_sort_Pipeline_sort_loop_j_fu_32.flow_control_loop_pipe_sequential_init_U", "Parent" : "13"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_copy_top_k_fu_159", "Parent" : "1", "Child" : ["17"],
		"CDFG" : "knn_distance_and_sort_Pipeline_copy_top_k",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "top_k_labels_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_k_labels_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_k_labels_1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "labels", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "copy_top_k", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_distance_and_sort_fu_176.grp_knn_distance_and_sort_Pipeline_copy_top_k_fu_159.flow_control_loop_pipe_sequential_init_U", "Parent" : "16"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193", "Parent" : "0", "Child" : ["19", "20", "22", "25"],
		"CDFG" : "knn_majority_vote",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "38", "EstimateLatencyMax" : "38",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "top_k_labels_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_read_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_read_11", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.counts_U", "Parent" : "18"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42", "Parent" : "18", "Child" : ["21"],
		"CDFG" : "knn_majority_vote_Pipeline_VITIS_LOOP_95_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "12", "EstimateLatencyMax" : "12",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "counts", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_95_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_95_1_fu_42.flow_control_loop_pipe_sequential_init_U", "Parent" : "20"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48", "Parent" : "18", "Child" : ["23", "24"],
		"CDFG" : "knn_majority_vote_Pipeline_VITIS_LOOP_106_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "8", "EstimateLatencyMax" : "8",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "top_k_labels_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_read_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_k_labels_read_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "counts", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_106_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48.sparsemux_7_2_4_1_1_U43", "Parent" : "22"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_106_2_fu_48.flow_control_loop_pipe_sequential_init_U", "Parent" : "22"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59", "Parent" : "18", "Child" : ["26"],
		"CDFG" : "knn_majority_vote_Pipeline_VITIS_LOOP_119_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "12", "EstimateLatencyMax" : "12",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "counts", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "max_label_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_119_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_knn_majority_vote_fu_193.grp_knn_majority_vote_Pipeline_VITIS_LOOP_119_3_fu_59.flow_control_loop_pipe_sequential_init_U", "Parent" : "25"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_r_s_axi_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_x_test_m_axi_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_x_train_m_axi_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_y_test_m_axi_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_y_train_m_axi_U", "Parent" : "0"}]}
